#!/usr/bin/env bash
# tests/linux/installed_update_modules.sh — CAN A MACHINE THAT *UPDATED* LOAD A
# KERNEL MODULE, AND DOES THE UPDATE KEEP THE DRIVER LINES THE MACHINE ADDED?
#
# WHY INSTALLING FROM THE IMAGE PROVES NOTHING ABOUT THIS
# ======================================================
# Measured against the published 1.0.12 channel, 152 files shipped in the image
# and were in NO package -- among them thirty-four kernel modules (ext4, vfat,
# virtio_blk, virtio_net, evdev, overlay, squashfs, loop, the snd-hda stack)
# and the `modules.dep` table `modprobe` resolves through. 1.0.13 ships them:
# `hamnix-drivers-base` (34 modules + `modules.dep.base`), with `hamnix-base`
# depending on it.
#
# tests/linux/channel_covers_image.sh proves the files LEAVE here, and this
# tree has been shown the live tarball really carries 34 `.ko` files. NONE of
# that is the thing that matters. A machine INSTALLED from the image always had
# the modules -- user/hlinstall.ad copies the live root -- so an
# image-installed machine cannot tell you anything about this. The failure the
# 1.0.13 packages fix is invisible except on a machine that UPDATES:
#
#   * does `hpm update` actually PULL a package that is brand new in the
#     channel, when the only thing naming it is a dependency line that appeared
#     in the version being upgraded to? (`hpm update` upgrades INSTALLED
#     packages; nothing is installed because it is new.)
#   * do the modules ARRIVE, and does the machine end up with a modules.dep
#     it can RESOLVE A NAME THROUGH -- not a file at the right path?
#   * and the risky half: `modules.dep` is MACHINE STATE. depmod generated it
#     over the modules THAT machine has, and hamnix-drivers-drm, -gpu-intel and
#     -gpu-nouveau each `echo '<line>' >> modules.dep` from their install
#     hooks. hamnix-drivers-base ships `modules.dep.base` and its hook
#     PREPENDS it (`cat base dep > new; mv new dep`), because user/modprobe.ad
#     takes the FIRST matching line. If it replaced instead, the machine would
#     keep i915.ko on disk and lose the only line that lets `modprobe i915`
#     name it -- a silent brick of that driver.
#
# THE MACHINE THIS GATE BUILDS, AND WHY IT IS THE HARD CASE
# =========================================================
# One disk, real UEFI + ext4, installed at a version BELOW the live one from a
# channel that models the pre-1.0.13 one: hamnix-drivers-base is REMOVED from
# it, and removed from hamnix-base's dependency list, so the machine's history
# contains no such package and never could have.
#
# Then the machine is put into the two states that make the questions
# answerable, and both are states a real machine reaches:
#
#   A. vfat.ko AND fat.ko ARE DELETED from the disk, and the two of them are
#      taken out of /etc/modules. That is a machine that lost a driver -- and
#      on the 1.0.12 channel it could NEVER get it back, because no package
#      carried the file. Taking them out of /etc/modules is what makes the
#      question modprobe's: linuxinit loads /etc/modules by ABSOLUTE PATH at
#      boot, so a module listed there is in the kernel before any test runs and
#      resolving its NAME was never exercised. /etc/modules is the operator's
#      file (hamnix-drivers-base deliberately does not touch it -- see the
#      8192-byte note in scripts/hamlinux_packages.py), so this is a supported
#      state, not a broken one.
#
#   B. THE MACHINE'S OWN modules.dep IS STALE ABOUT vfat: its line reads
#      `kernel/fs/fat/vfat.ko: kernel/fs/fat/fat-STALE-NOT-HERE.ko`. That is
#      the whole reason the package ships a table at all. It also makes the
#      PREPEND DIRECTION measurable rather than assumed: after the update the
#      fresh line must be found FIRST. A hook that appended, or that merged the
#      other way round, leaves the stale line winning and `modprobe vfat`
#      still fails -- with the .ko sitting right there on the disk.
#
#   C. A DRIVER PACKAGE'S APPENDED LINES ARE ALREADY IN THE TABLE. The image
#      is built with HAMLINUX_MODULES_LATE=8021q, so 8021q.ko and its chain are
#      ON THE DISK and 8021q's line is WITHHELD from the build-time table --
#      exactly the state a machine is in the instant `hpm install
#      hamnix-drivers-gpu-intel` puts i915.ko on it. Boot 1 then appends the
#      dependency lines with the very `echo '<line>' >> '<table>'` a driver
#      hook emits, GENERATED BY scripts/hamlinux_packages.py's OWN generator so
#      a change that broke the real hook breaks this too.
#
# WHAT IS ASSERTED, AND NONE OF IT IS A FILE EXISTING
# ===================================================
# Boot 3, on the same disk, nothing rebuilt:
#
#   1. `modprobe -v vfat` -> fat, then vfat, and BOTH ARE IN /proc/modules --
#      the kernel's own list -- with fat's used-by column naming vfat. That one
#      sentence requires the .ko files to have ARRIVED over the update AND a
#      correct vfat line to be found BEFORE the machine's stale one. Neither
#      half can be satisfied by an exit code or a path.
#   2. `modprobe -v 8021q` -> garp, stp, mrp, llc, 8021q all in /proc/modules.
#      The ONLY line in the table that names 8021q is the one the machine
#      appended before the update. If the merge had replaced the table, this
#      module is on the disk and unnameable.
#   3. The machine's STALE vfat line is STILL IN THE TABLE, after the fresh
#      one. That is what makes "the shipped lines won" a statement about ORDER
#      rather than about a rewrite -- prepend, not replace.
#
# And boot 2 asserts the negatives on the same disk before the update: the .ko
# files are gone, `modprobe vfat` FAILS, vfat and fat are in nobody's kernel --
# while `modprobe 8021q` already WORKS, so the appended lines are known to be
# live going in and their survival is a real question.
#
# NO VERSION IS HARD-CODED AGAINST THE LIVE REPOSITORY
# ====================================================
# Publishing 1.0.8 once broke a test that hard-coded 1.0.8. The live version is
# READ from https://255.one/linux/index.json at run time and the "old" one is
# DERIVED strictly below it (never below 1.0.0 -- hamnix-base declares
# hamnix-init>=1). If no version below the live one can be derived, this says
# so and stops rather than measuring something else in the same shape.
#
# DELIBERATELY BREAKING IT -- both arms exist because "it went green" has to be
# a statement about the mechanism and not about this file reaching its end:
#
#   HAMLINUX_MODUPD_NOUPDATE=1  boot 2 does everything EXCEPT `hpm update`.
#       The modules never arrive; boot 3 must go red on question 1.
#   HAMLINUX_MODUPD_CLOBBER=1   boot 2 runs the update and then does what a
#       REPLACING hook would have done -- `cp modules.dep.base modules.dep`.
#       vfat still resolves (the shipped table has it) and 8021q does NOT:
#       boot 3 must go red on question 2, which is the appended-driver-line
#       failure this whole design exists to avoid.
#
# Usage: tests/linux/installed_update_modules.sh [b1s] [b2s] [b3s]
#   HAMLINUX_MODUPD_REUSE=1    reuse the staged image root + local channel
set -uo pipefail
PROJ_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJ_ROOT"

export HAMLINUX_VNC="${HAMLINUX_VNC:-none}"
export HAMLINUX_DISTRO_RO="${HAMLINUX_DISTRO_RO:-1}"
# /tmp on the dev box is a 16 GB tmpfs -- the owner's RAM. Nothing large here.
export TMPDIR="${TMPDIR:-$PROJ_ROOT/build/tmp}"
mkdir -p "$TMPDIR"

WAIT1="${1:-600}"
WAIT2="${2:-900}"
WAIT3="${3:-480}"
PKG=hamnix-base            # the package whose NEW dependency must be pulled in
DRVPKG=hamnix-drivers-base # the package that is new in the channel
CHANNEL_URL="${HAMLINUX_MODUPD_URL:-https://255.one/linux/index.json}"
LIVE_BASE="$(dirname "$CHANNEL_URL")/"

WORK="${HAMLINUX_MODUPD_WORK:-build/modupd}"; mkdir -p "$WORK"
IMG=build/image
DISK="$IMG/modupd.img"
REPO="$WORK/repo"
EXTRA="$WORK/extra"
NOUPD="${HAMLINUX_MODUPD_NOUPDATE:-0}"
CLOBBER="${HAMLINUX_MODUPD_CLOBBER:-0}"

# The module whose FILES must arrive, and its dependency. Chosen because it is
# a filesystem: nothing here touches hardware, in the VM or out of it.
MOD=vfat
DEPMOD_=fat
LATE=8021q                  # the "driver package" module already on the disk

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "PASS: $*"; }
bad() { FAIL=$((FAIL+1)); echo "FAIL: $*"; }
say() { echo "[modupd] $*"; }

command -v python3 >/dev/null || { echo "need python3" >&2; exit 1; }

# =========================================================================
# 1. WHAT IS THE LIVE CHANNEL AT, RIGHT NOW?
# =========================================================================
# Asked, never assumed, and a channel that cannot be reached is a failure of
# the run rather than something to fall back from: falling back to a local
# channel would answer a different question in the same shape, which is the
# exact failure NORTH_STAR.md names.
say "asking $CHANNEL_URL what it serves"
curl -fsS --max-time 60 "$CHANNEL_URL" -o "$WORK/live-index.json" || {
    echo "FAIL: cannot reach $CHANNEL_URL -- this gate has nothing to measure" >&2
    exit 1; }
livever() { PKG="$1" python3 - "$WORK/live-index.json" <<'PY'
import json, os, sys
d = json.load(open(sys.argv[1]))
for r in d["packages"]:
    if r["name"] == os.environ["PKG"]:
        print(r["version"]); break
PY
}
LIVEVER="$(livever "$PKG")"
DRVVER="$(livever "$DRVPKG")"
[ -n "$LIVEVER" ] || { echo "FAIL: the channel carries no $PKG at all" >&2; exit 1; }
[ -n "$DRVVER" ] || {
    echo "FAIL: the live channel carries NO $DRVPKG. That is the finding:" >&2
    echo "      the kernel modules are in the image and in no package, so an" >&2
    echo "      installed machine can never receive a fix to them." >&2; exit 1; }

# THE "OLD" VERSION, DERIVED -- strictly below the live one and never below
# 1.0.0 (hamnix-base declares hamnix-init>=1; a 0.x would make the package
# refuse to install for a reason that is not what is being measured).
OLDVER="$(LIVEVER="$LIVEVER" python3 <<'PY'
import os, sys
try:
    a, b, c = (int(x) for x in os.environ["LIVEVER"].split("."))
except ValueError:
    sys.exit(1)
if c > 0:   print("%d.%d.0" % (a, b))
elif b > 0: print("%d.0.0" % a)
elif a > 1: print("%d.0.0" % (a - 1))
else:       sys.exit(1)
PY
)"
[ -n "$OLDVER" ] || {
    echo "FAIL: the channel is at $LIVEVER and no version below it still" >&2
    echo "      satisfies hamnix-init>=1. Nothing is measured rather than" >&2
    echo "      measuring the wrong thing." >&2; exit 1; }
OLDVER="$OLDVER" LIVEVER="$LIVEVER" python3 <<'PY' || {
import os, sys
def key(v): return [int(x) for x in v.split(".")]
sys.exit(0 if key(os.environ["OLDVER"]) < key(os.environ["LIVEVER"]) else 1)
PY
    echo "FAIL: derived old version $OLDVER does not sort below $LIVEVER" >&2; exit 1; }
say "the live channel serves $PKG $LIVEVER and $DRVPKG $DRVVER"
say "this machine will be installed at $OLDVER, from a channel with NO $DRVPKG"

# The live hamnix-base must actually DEPEND on the driver package -- that
# dependency line is the entire mechanism by which a brand-new package reaches
# a machine that already exists. Without it there is nothing to measure.
if PKG="$PKG" DRV="$DRVPKG" python3 - "$WORK/live-index.json" <<'PY'
import json, os, sys
d = json.load(open(sys.argv[1]))
for r in d["packages"]:
    if r["name"] == os.environ["PKG"]:
        sys.exit(0 if any(t.split(">")[0].split("=")[0] == os.environ["DRV"]
                          for t in r.get("depends", [])) else 1)
sys.exit(1)
PY
then
    ok "the live $PKG $LIVEVER declares a dependency on $DRVPKG -- the only thing that can pull a brand-new package onto a machine that already exists"
else
    bad "the live $PKG does not depend on $DRVPKG: nothing would ever pull it onto an updating machine"
fi

# =========================================================================
# 2. THE BYTES 255.one IS SERVING, FETCHED BY THE HOST TOO.
# =========================================================================
DRV_URL="$(PKG="$DRVPKG" python3 - "$WORK/live-index.json" <<'PY'
import json, os, sys
d = json.load(open(sys.argv[1]))
base = d.get("url", "")
for r in d["packages"]:
    if r["name"] == os.environ["PKG"]:
        u = r["url"]
        print(u if u.startswith("http") else base.rstrip("/") + "/" + u)
        break
PY
)"
say "fetching $DRV_URL"
curl -fsS --max-time 300 "$DRV_URL" -o "$WORK/live-drv.tar.gz" || {
    echo "FAIL: cannot download the live $DRVPKG tarball" >&2; exit 1; }
rm -rf "$WORK/drvunpack"; mkdir -p "$WORK/drvunpack"
tar xzf "$WORK/live-drv.tar.gz" -C "$WORK/drvunpack" || {
    echo "FAIL: the live tarball did not unpack" >&2; exit 1; }
DRVROOT="$WORK/drvunpack/$DRVPKG-$DRVVER/files"

# The KERNEL RELEASE this gate's image is built for. The published package was
# built for whatever kernel the publisher had; if they differ, the paths do not
# line up and NOTHING below would be measuring what it says. Say so and stop.
KVER="$(basename "$(ls -d "$IMG"/root/lib/modules/*/ 2>/dev/null | head -1)")"
[ -n "$KVER" ] || KVER="$(basename "$(ls -1 /boot/vmlinuz-* | sort -V | tail -1)" | sed 's/^vmlinuz-//')"
[ -d "$DRVROOT/lib/modules/$KVER" ] || {
    echo "FAIL: the live $DRVPKG is built for $(ls "$DRVROOT/lib/modules" 2>/dev/null | tr '\n' ' ')" >&2
    echo "      and this host's image is $KVER. The channel is not serving" >&2
    echo "      modules for the kernel this machine runs; that is the finding." >&2
    exit 1; }
GDIR="/lib/modules/$KVER"
KO="$GDIR/kernel/fs/fat/$MOD.ko"
KODEP="$GDIR/kernel/fs/fat/$DEPMOD_.ko"
DEPTBL="$GDIR/modules.dep"
BASETBL="$GDIR/modules.dep.base"

# The digests of the two modules AS THE CHANNEL SERVES THEM. No index field
# and no path can satisfy an assertion made on these.
for f in "$KO" "$KODEP" "$BASETBL"; do
    [ -f "$DRVROOT$f" ] || {
        echo "FAIL: the live $DRVPKG carries no $f" >&2; exit 1; }
done
LIVE_KO_MD5="$(md5sum "$DRVROOT$KO" | cut -d' ' -f1)"
LIVE_KODEP_MD5="$(md5sum "$DRVROOT$KODEP" | cut -d' ' -f1)"
ok "the live $DRVPKG carries $(find "$DRVROOT" -name '*.ko' | wc -l) .ko files, $MOD.ko among them (md5 $LIVE_KO_MD5) and the $(grep -c . "$DRVROOT$BASETBL")-line $BASETBL"
if grep -q "^kernel/fs/fat/$MOD\.ko: .*kernel/fs/fat/$DEPMOD_\.ko" "$DRVROOT$BASETBL"; then
    ok "and its shipped table names $MOD's dependency: $(grep "^kernel/fs/fat/$MOD\.ko:" "$DRVROOT$BASETBL")"
else
    bad "the shipped $BASETBL has no $MOD line naming $DEPMOD_ -- there would be nothing for the prepend to fix"
fi
# The hook's DIRECTION, read out of the published tarball rather than out of
# the generator that wrote it.
HOOK="$WORK/drvunpack/$DRVPKG-$DRVVER/install.hamsh"
if [ -f "$HOOK" ] && grep -q "^cat '$BASETBL' '$DEPTBL' > '$DEPTBL.new'" "$HOOK"; then
    ok "the PUBLISHED install hook prepends: $(grep "^cat '" "$HOOK")"
else
    bad "the published $DRVPKG install hook does not prepend its table onto the machine's; the appended driver lines would not survive"
fi

# =========================================================================
# 3. The image root: 8021q ON THE DISK and WITHHELD from the table.
# =========================================================================
if [ "${HAMLINUX_MODUPD_REUSE:-0}" = 1 ] && [ -f "$IMG/initramfs.cpio.gz" ]; then
    say "reusing the staged image root (HAMLINUX_MODUPD_REUSE=1)"
else
    say "staging the image root ($LATE on disk, withheld from modules.dep)"
    HAMLINUX_JOBS="${HAMLINUX_JOBS:-4}" HAMLINUX_MODULES_LATE="$LATE" \
        nice -n 15 scripts/hamlinux_image.sh >"$WORK/image.log" 2>&1 || {
        echo "FAIL image build"; tail -20 "$WORK/image.log"; exit 1; }
fi
IROOT="$IMG/root"
[ -f "$IROOT$DEPTBL" ] || { echo "FAIL: the image staged no $DEPTBL" >&2; exit 1; }
if ls "$IROOT$GDIR"/kernel/net/8021q/8021q.ko >/dev/null 2>&1; then
    ok "$LATE.ko is on the image's disk"
else
    bad "$LATE.ko is not on the image's disk -- the appended-driver-line half would prove nothing"
fi
if grep -q "^kernel/net/8021q/8021q\.ko:" "$IROOT$DEPTBL"; then
    bad "$LATE is already in the build-time table -- that is not the post-install state a driver package leaves"
else
    ok "$LATE is NOT in the build-time table -- exactly the state 'hpm install hamnix-drivers-gpu-intel' leaves"
fi

# --- the exact lines a driver package's install hook appends --------------
# Generated by scripts/hamlinux_packages.py's OWN generator. What boot 1
# appends is the thing the driver packages really ship, so a change that broke
# the real hook has to break this too.
python3 - "$KVER" "$LATE" > "$WORK/hooklines" <<'PY'
import importlib.util, os, sys
kver, mod = sys.argv[1], sys.argv[2]
spec = importlib.util.spec_from_file_location(
    "hp", os.path.join(os.getcwd(), "scripts/hamlinux_packages.py"))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
chain = m.modprobe_chain(kver, mod)
if not chain:
    sys.exit("no modprobe chain for %s" % mod)
prefix = "/lib/modules/%s/" % kver
canon = []
for ko in chain:
    rel = ko[len(prefix):]
    for ext in (".xz", ".gz", ".zst"):
        if rel.endswith(ext):
            rel = rel[:-len(ext)]
    canon.append(prefix + rel)
lines = m.dep_lines_for_paths(kver, canon)
if not lines:
    sys.exit("dep_lines_for_paths returned nothing")
for l in lines:
    print("echo '%s' >> '/lib/modules/%s/modules.dep'" % (l, kver))
PY
[ -s "$WORK/hooklines" ] || { echo "FAIL: could not generate $LATE's hook lines"; exit 1; }
LATE_LINE="$(grep -o "^echo 'kernel/net/8021q/8021q\.ko:[^']*'" "$WORK/hooklines" \
             | sed "s/^echo '//; s/'$//")"
[ -n "$LATE_LINE" ] || { echo "FAIL: no $LATE line among the generated hook lines"; exit 1; }
say "the driver-hook line the machine will append: $LATE_LINE"

# =========================================================================
# 4. The channel the machine was installed from -- WITHOUT the module package.
# =========================================================================
PORT="$(python3 - <<'PY'
import socket
s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()
PY
)"
BASE="http://10.0.2.2:$PORT/"
if [ "${HAMLINUX_MODUPD_REUSE:-0}" = 1 ] && [ -f "$REPO/linux/index.json" ]; then
    say "reusing the local channel at $OLDVER (HAMLINUX_MODUPD_REUSE=1)"
else
    say "building the local channel at $OLDVER (the machine's original install)"
    nice -n 15 scripts/hamlinux_packages.py --out "$REPO" --version "$OLDVER" \
        --channel linux --base-url "$BASE" >"$WORK/repo.log" 2>&1 || {
        echo "FAIL channel build"; tail -25 "$WORK/repo.log"; exit 1; }
fi

# THE CHANNEL THE PRE-1.0.13 ONE WAS: no hamnix-drivers-base anywhere, and
# hamnix-base does not name it. The tarball is deleted, the index entry is
# deleted, the dependency is struck from hamnix-base's index entry AND from
# the PKGINFO inside its tarball (whose sha256 is recomputed) -- so nothing
# the guest can read mentions the package. The ONLY difference from the real
# 1.0.12 channel is the version numbers on everything else.
say "removing $DRVPKG from the original-install channel (modelling pre-1.0.13)"
REPO="$REPO" DRV="$DRVPKG" PKG="$PKG" OLDVER="$OLDVER" python3 <<'PY' \
    || { echo "FAIL: could not strip $DRVPKG from the local channel"; exit 1; }
import hashlib, io, json, os, tarfile
repo, drv, pkg, ver = (os.environ["REPO"], os.environ["DRV"],
                       os.environ["PKG"], os.environ["OLDVER"])
lin = os.path.join(repo, "linux")
tarpath = os.path.join(lin, "packages", "%s-%s.tar.gz" % (drv, ver))
if os.path.exists(tarpath):
    os.unlink(tarpath)
else:
    raise SystemExit("the local channel had no %s to remove -- it was never "
                     "built, so this run would not be modelling anything" % drv)

# Strike the dependency out of hamnix-base's PKGINFO, in place, and keep the
# tarball a real tarball: hpm verifies the sha256 before it unpacks a byte.
btar = os.path.join(lin, "packages", "%s-%s.tar.gz" % (pkg, ver))
top = "%s-%s" % (pkg, ver)
members = []
with tarfile.open(btar, "r:gz") as tf:
    for ti in tf.getmembers():
        members.append((ti, tf.extractfile(ti).read() if ti.isfile() else None))
hit = False
out = io.BytesIO()
with tarfile.open(fileobj=out, mode="w:gz", compresslevel=9,
                  format=tarfile.GNU_FORMAT) as tw:
    for ti, data in members:
        if ti.name == top + "/PKGINFO":
            txt = data.decode()
            new = []
            for line in txt.splitlines():
                if line.startswith("depends:"):
                    terms = [t.strip() for t in line[len("depends:"):].split(",")]
                    keep = [t for t in terms
                            if t.split(">")[0].split("=")[0].strip() != drv]
                    if len(keep) != len(terms):
                        hit = True
                    line = "depends: " + ", ".join(keep)
                new.append(line)
            data = ("\n".join(new) + "\n").encode()
            ti.size = len(data)
        if data is None:
            tw.addfile(ti)
        else:
            tw.addfile(ti, io.BytesIO(data))
if not hit:
    raise SystemExit("%s's PKGINFO did not name %s" % (pkg, drv))
raw = out.getvalue()
open(btar, "wb").write(raw)

ipath = os.path.join(lin, "index.json")
index = json.load(open(ipath))
before = len(index["packages"])
index["packages"] = [e for e in index["packages"] if e["name"] != drv]
if len(index["packages"]) == before:
    raise SystemExit("the local index had no %s entry" % drv)
for e in index["packages"]:
    if e["name"] == pkg:
        e["depends"] = [t for t in e.get("depends", [])
                        if t.split(">")[0].split("=")[0] != drv]
        e["sha256"] = hashlib.sha256(raw).hexdigest()
        e["size"] = len(raw)
index["url"] = os.environ.get("BASEURL", index.get("url"))
with open(ipath, "w") as fh:
    json.dump(index, fh, indent=2); fh.write("\n")
PY
BASEURL="$BASE" REPO="$REPO" python3 <<'PY'
import json, os
p = os.path.join(os.environ["REPO"], "linux", "index.json")
d = json.load(open(p)); d["url"] = os.environ["BASEURL"]
json.dump(d, open(p, "w"), indent=2); open(p, "a").write("\n")
PY
if grep -q "$DRVPKG" "$REPO/linux/index.json"; then
    bad "the original-install channel still mentions $DRVPKG somewhere"
else
    ok "the original-install channel carries no $DRVPKG at all -- the machine's history cannot contain it"
fi

# The local channel is SIGNED and the guest gets the matching public key: the
# install this machine's history is made of takes the path a real one takes,
# with no --allow-unsigned anywhere in this file.
mkdir -p "$EXTRA/etc/hpm"
python3 scripts/hpm_sign.py keygen --out-pub "$EXTRA/etc/hpm/test-trusted.pub" \
    --out-sec "$WORK/test.sec" >/dev/null || {
    echo "FAIL: cannot mint a signing key"; exit 1; }
python3 scripts/hpm_sign.py sign "$REPO/linux/index.json" "$WORK/test.sec" \
    "$REPO/linux/index.json.sig" || {
    echo "FAIL: cannot sign the local index"; exit 1; }

python3 -m http.server "$PORT" --bind 127.0.0.1 --directory "$REPO" \
    >"$WORK/http.log" 2>&1 &
HTTPD=$!
cleanup() {
    kill "$HTTPD" 2>/dev/null; wait "$HTTPD" 2>/dev/null
    [ -n "${VM:-}" ] && kill "$VM" 2>/dev/null
}
trap cleanup EXIT
sleep 1
curl -fsS "http://127.0.0.1:$PORT/linux/index.json" >/dev/null || {
    echo "FAIL: the local channel is not being served"; exit 1; }
say "the original-install channel is served at $BASE (pid $HTTPD)"

# =========================================================================
# 5. THE MACHINE'S OWN STATE, staged onto the installed root.
# =========================================================================
# /etc/modules WITHOUT the fat pair, so nothing but modprobe can put them in
# the kernel; and a modules.dep whose vfat line is STALE, which is the state
# the shipped table exists to repair. Both are files the distribution does not
# own -- scripts/hamlinux_packages.py excludes them for exactly that reason.
mkdir -p "$EXTRA$GDIR" "$EXTRA/etc"
grep -v '/kernel/fs/fat/' "$IROOT/etc/modules" > "$EXTRA/etc/modules"
if [ "$(grep -c . "$EXTRA/etc/modules")" -lt 20 ] ||
   grep -q '/kernel/fs/fat/' "$EXTRA/etc/modules"; then
    bad "could not build an /etc/modules without the fat pair"
else
    ok "the machine's /etc/modules lists $(grep -c . "$EXTRA/etc/modules") modules and NEITHER $MOD nor $DEPMOD_ -- so only modprobe can load them"
fi
STALE="kernel/fs/fat/$DEPMOD_-STALE-NOT-HERE.ko"
sed "s|^kernel/fs/fat/$MOD\.ko: .*|kernel/fs/fat/$MOD.ko: $STALE|" \
    "$IROOT$DEPTBL" > "$EXTRA$DEPTBL"
if grep -q "^kernel/fs/fat/$MOD\.ko: $STALE\$" "$EXTRA$DEPTBL" &&
   ! cmp -s "$IROOT$DEPTBL" "$EXTRA$DEPTBL"; then
    ok "the machine's own table is STALE about $MOD: $(grep "^kernel/fs/fat/$MOD\.ko:" "$EXTRA$DEPTBL")"
else
    bad "could not make the machine's table stale about $MOD -- the prepend direction would not be measurable"
fi

# =========================================================================
# 6. The three boot scripts.
# =========================================================================
# Every one of them `source /etc/rc.boot.installed` -- the REAL installed rc.
_dump() {   # _dump <phase> <tag>: the kernel's own list and the machine's table
    cat <<D
echo '[modupd] $1 MODULES-$2-BEGIN'
cat /proc/modules
echo '[modupd] $1 MODULES-$2-END'
echo '[modupd] $1 TABLE-$2-BEGIN'
cat '$DEPTBL'
echo '[modupd] $1 TABLE-$2-END'
echo '[modupd] $1 KOLS-$2-BEGIN'
ls -l '$KO'
ls -l '$KODEP'
echo '[modupd] $1 KOLS-$2-END'
D
}

{
cat <<RC
source '/etc/rc.boot.installed'

echo '[modupd] ===== PHASE 1: the machine this distribution shipped BEFORE'
echo '[modupd]               the kernel modules were in any package'
date
dhcpc
echo '[modupd] p1 dhcpc status:' \$status

echo '[modupd] p1 refresh the original-install channel'
hpm --repo=$BASE --trusted-key=/etc/hpm/test-trusted.pub refresh
echo '[modupd] p1 refresh status:' \$status
echo '[modupd] p1 install $PKG from the original-install channel'
hpm --repo=$BASE --trusted-key=/etc/hpm/test-trusted.pub install $PKG
echo '[modupd] p1 install status:' \$status
echo '[modupd] p1 LIST-BEGIN'
hpm list
echo '[modupd] p1 LIST-END'

# THE MACHINE LOSES THE DRIVER. On the channel it was installed from, no
# package carries this file, so nothing it can ever run puts it back.
echo '[modupd] p1 deleting the $MOD driver and its dependency'
rm '$KO'
echo '[modupd] p1 rm $MOD status:' \$status
rm '$KODEP'
echo '[modupd] p1 rm $DEPMOD_ status:' \$status

# AND IT GAINS A DRIVER PACKAGE'S APPENDED LINES -- the exact echo/>> a real
# install hook emits, generated by the generator that writes the real ones.
echo '[modupd] p1 appending the driver-package lines for $LATE'
RC
cat "$WORK/hooklines"
cat <<RC
echo '[modupd] p1 append status:' \$status
RC
_dump p1 AFTER
cat <<'RC'
echo '[modupd] PHASE1 DONE'
cp /etc/rc.phase2 /etc/rc.boot
echo '[modupd] p1 armed the next boot'
reboot
RC
} > "$WORK/rc.phase1"

{
cat <<RC
source '/etc/rc.boot.installed'

echo '[modupd] ===== PHASE 2: the machine as it stands, and then hpm update'
date
dhcpc
echo '[modupd] p2 dhcpc status:' \$status
RC
_dump p2 BEFORE
cat <<RC

# THE NEGATIVES, ON THIS DISK, BEFORE ANYTHING IS UPDATED.
echo '[modupd] p2 MISS-BEGIN'
modprobe -v $MOD
echo '[modupd] p2 miss status:' \$status
echo '[modupd] p2 MISS-END'

# ...while the lines a driver package appended ALREADY WORK, so their survival
# across the update is a real question and not a vacuous one.
echo '[modupd] p2 LATE-BEGIN'
modprobe -v $LATE
echo '[modupd] p2 late status:' \$status
echo '[modupd] p2 LATE-END'
echo '[modupd] p2 LATEMOD-BEGIN'
cat /proc/modules
echo '[modupd] p2 LATEMOD-END'
RC
} > "$WORK/rc.phase2"

if [ "$NOUPD" = 1 ]; then
cat >> "$WORK/rc.phase2" <<RC

# HAMLINUX_MODUPD_NOUPDATE=1: the update is DELIBERATELY NOT RUN. Everything
# else is identical, so whatever boot 3 says is a statement about the update.
echo '[modupd] p2 THE UPDATE WAS DELIBERATELY SKIPPED (HAMLINUX_MODUPD_NOUPDATE=1)'
RC
else
cat >> "$WORK/rc.phase2" <<RC

# THE COMMAND THE OWNER TYPES, WITH NOTHING ADDED TO IT, AGAINST THE REAL
# REPOSITORY: no --repo, no --allow-unsigned, no key this test staged.
echo '[modupd] p2 ----- hpm refresh (no flags, the real repository)'
hpm refresh
echo '[modupd] p2 refresh status:' \$status
echo '[modupd] p2 ----- hpm update (no flags, the real repository)'
hpm update
echo '[modupd] p2 update status:' \$status
echo '[modupd] p2 LIST-BEGIN'
hpm list
echo '[modupd] p2 LIST-END'
echo '[modupd] p2 md5 of $KO after the update:'
md5sum '$KO'
echo '[modupd] p2 md5 of $KODEP after the update:'
md5sum '$KODEP'
RC
fi

if [ "$CLOBBER" = 1 ]; then
cat >> "$WORK/rc.phase2" <<RC

# HAMLINUX_MODUPD_CLOBBER=1: do what a hook that REPLACED the table instead of
# prepending would have done. The machine keeps 8021q.ko and loses the only
# line that lets modprobe name it.
echo '[modupd] p2 CLOBBERING the table with the package copy (the wrong hook)'
cp '$BASETBL' '$DEPTBL'
echo '[modupd] p2 clobber status:' \$status
RC
fi

{
_dump p2 AFTER
cat <<'RC'
date
echo '[modupd] PHASE2 DONE'
cp /etc/rc.phase3 /etc/rc.boot
echo '[modupd] p2 armed the next boot'
reboot
RC
} >> "$WORK/rc.phase2"

{
cat <<RC
source '/etc/rc.boot.installed'

echo '[modupd] ===== PHASE 3: the same disk, nothing rebuilt.'
date
echo '[modupd] p3 LIST-BEGIN'
hpm list
echo '[modupd] p3 LIST-END'
# WHICH REPOSITORY DOES THIS MACHINE STILL BELIEVE IT SUBSCRIBES TO? An
# installed machine that has taken one update must still be able to take the
# next one, and this file is the only thing that decides where it looks.
echo '[modupd] p3 CHANNELS-BEGIN'
cat /etc/hpm/channels
echo '[modupd] p3 CHANNELS-END'
RC
_dump p3 BEFORE
cat <<RC

# THE SENTENCE THIS WHOLE FILE EXISTS FOR. Neither module is in /etc/modules,
# so nothing but this command can put them in the kernel.
echo '[modupd] p3 LOAD-BEGIN'
modprobe -v $MOD
echo '[modupd] p3 load status:' \$status
echo '[modupd] p3 LOAD-END'

# AND THE LINES THE MACHINE APPENDED, which only survive if the merge prepended.
echo '[modupd] p3 LATE-BEGIN'
modprobe -v $LATE
echo '[modupd] p3 late status:' \$status
echo '[modupd] p3 LATE-END'
RC
_dump p3 AFTER
cat <<'RC'
echo '[modupd] p3 LSMOD-BEGIN'
lsmod
echo '[modupd] p3 LSMOD-END'
date
echo '[modupd] PHASE3 DONE'
# End the machine rather than leaving pid 1 on a prompt: hamsh falling through
# to read the console holds the VM for the whole remaining budget.
reboot
RC
} > "$WORK/rc.phase3"

cp "$WORK/rc.phase2" "$EXTRA/etc/rc.phase2"
cp "$WORK/rc.phase3" "$EXTRA/etc/rc.phase3"

# =========================================================================
# 7. Install a disk.
# =========================================================================
say "building the installed disk"
HAMLINUX_DISK_RC="$WORK/rc.phase1" HAMLINUX_DISK_EXTRA="$EXTRA" \
    nice -n 15 scripts/hamlinux_disk.sh "$DISK" 3G >"$WORK/build.log" 2>&1 || {
    echo "FAIL disk build"; tail -20 "$WORK/build.log"; exit 1; }
DISK_SUM_BEFORE="$(md5sum "$DISK" | cut -d' ' -f1)"

# =========================================================================
# 8. Boot it three times.
# =========================================================================
boot() {   # boot <logfile> <seconds>
    local log="$1" secs="$2"
    ( sleep 5 ) | HAMLINUX_DISK="$DISK" \
        timeout "$((secs + 25))" scripts/hamlinux_vm.sh disk --timeout "$secs" \
        >"$log" 2>&1 &
    VM=$!
    wait "$VM" 2>/dev/null
    VM=""
}
say "boot 1 of 3: the install that gives this machine its history (up to ${WAIT1}s)"
boot "$WORK/boot1.log" "$WAIT1"
say "boot 2 of 3: the machine as it stands, then the update (up to ${WAIT2}s)"
boot "$WORK/boot2.log" "$WAIT2"
say "boot 3 of 3: the same disk, and one modprobe (up to ${WAIT3}s)"
boot "$WORK/boot3.log" "$WAIT3"
DISK_SUM_AFTER="$(md5sum "$DISK" | cut -d' ' -f1)"

for n in 1 2 3; do
    echo
    echo "--------- boot $n transcript"
    grep -aE '^\[modupd\]|^rc\.boot:|^hpm:|^modprobe' "$WORK/boot$n.log" \
        | tr -d '\r' || tail -20 "$WORK/boot$n.log"
done
echo

# =========================================================================
# 9. The questions.
# =========================================================================
LOG=""
sect() {  # sect <phase> <name> -> the lines between the two markers
    sed -n "/\[modupd\] $1 $2-BEGIN/,/\[modupd\] $1 $2-END/p" "$LOG" | tr -d '\r'
}
has() {   # has <regex> in $LOG
    grep -aqE "$1" "$LOG"
}
inker() { # inker <blob> <module> -> 0 if the kernel's own list has it
    printf '%s\n' "$1" | grep -q "^${2//-/_} "
}

echo "--- boot 1: the machine gets its history"
LOG="$WORK/boot1.log"
has 'rc\.boot: hamnix-linux \(installed\)' \
    && ok "the installed root came online" \
    || bad "the installed root never came online"
has '\[modupd\] p1 dhcpc status: 0' && ok "dhcpc took a lease" || bad "dhcpc failed"
has '\[modupd\] p1 install status: 0' \
    && ok "the original install of $PKG exited 0" \
    || bad "the original install did not exit 0"
P1LIST="$(sect p1 LIST)"
if printf '%s\n' "$P1LIST" | grep -qE "$PKG[^0-9]*$OLDVER"; then
    ok "and the machine records $PKG at $OLDVER"
else
    bad "the machine does not record $PKG at $OLDVER (got: $(printf '%s' "$P1LIST" | tr '\n' '|'))"
fi
if printf '%s\n' "$P1LIST" | grep -q "$DRVPKG"; then
    bad "$DRVPKG is installed on the ORIGINAL machine -- it is supposed to model the channel that never had it"
else
    ok "$DRVPKG is NOT installed: this is a machine from before the modules were in any package"
fi
has "\[modupd\] p1 rm $MOD status: 0" \
    && ok "the $MOD driver was deleted from the disk" \
    || bad "the $MOD driver was not deleted"
P1TBL="$(sect p1 TABLE-AFTER)"
if printf '%s\n' "$P1TBL" | grep -qF "$LATE_LINE"; then
    ok "the driver-package lines for $LATE are in the machine's table: $LATE_LINE"
else
    bad "the $LATE line a driver hook appends is not in the machine's table"
fi

echo
echo "--- boot 2: THE MACHINE BEFORE THE UPDATE (the negatives)"
LOG="$WORK/boot2.log"
P2MODS="$(sect p2 MODULES-BEFORE)"
if [ "$(printf '%s\n' "$P2MODS" | grep -c '^[a-z_0-9]* [0-9]')" -lt 5 ]; then
    bad "/proc/modules listed fewer than 5 modules -- not a machine this can be measured on"
else
    ok "/proc/modules is readable and lists $(printf '%s\n' "$P2MODS" | grep -c '^[a-z_0-9]* [0-9]') modules"
fi
for m in "$MOD" "$DEPMOD_" "$LATE"; do
    if inker "$P2MODS" "$m"; then
        bad "$m was already in the kernel before the update -- this proves nothing"
    else
        ok "$m is not in the kernel before the update"
    fi
done
P2KOLS="$(sect p2 KOLS-BEFORE)"
if printf '%s\n' "$P2KOLS" | grep -q "$KO\$"; then
    bad "$KO is still on the disk before the update -- the deletion did not take"
else
    ok "$KO is NOT on the disk before the update ($(printf '%s\n' "$P2KOLS" | grep -i 'no such\|open failed\|cannot' | head -1))"
fi
P2MISS="$(sect p2 MISS)"
if printf '%s\n' "$P2MISS" | grep -q 'miss status: 0'; then
    bad "modprobe $MOD EXITED 0 on a machine that has no $MOD.ko -- success-shaped, having loaded nothing"
else
    ok "modprobe $MOD exits non-zero on the pre-update machine: $(printf '%s\n' "$P2MISS" | grep -iE 'modprobe:' | head -1)"
fi
P2LATE="$(sect p2 LATE)"
P2LATEMOD="$(sect p2 LATEMOD)"
if printf '%s\n' "$P2LATE" | grep -q 'late status: 0' && inker "$P2LATEMOD" "$LATE"; then
    ok "$LATE DOES load before the update -- the appended driver lines are live going in, so their survival is a real question"
else
    bad "$LATE does not load even before the update; the appended-line half would be vacuous"
fi

if [ "$NOUPD" = 1 ]; then
    echo "modupd: NOTE HAMLINUX_MODUPD_NOUPDATE=1 -- the update was deliberately not run"
    has '\[modupd\] p2 THE UPDATE WAS DELIBERATELY SKIPPED' \
        && ok "and the run says so out loud" || bad "the skip was not announced"
else
    echo
    echo "--- boot 2, continued: hpm update, no flags, against $LIVE_BASE"
    has '\[modupd\] p2 refresh status: 0' \
        && ok "a bare 'hpm refresh' TRUSTS the real repository" \
        || bad "a bare 'hpm refresh' did not exit 0"
    # AND IT WENT TO THE RIGHT CHANNEL. `main` holds Hamnix NATIVE binaries;
    # `linux` holds this userland. A machine that installed hamnix-base used to
    # be rewritten to `main` by the hpm package's own copy of
    # /etc/hpm/channels, and every refresh afterwards died on a 404 for
    # https://255.one/main/index.json.sig -- the machine cut off from its own
    # repository by the act of installing from it.
    has "hpm: (fetching channel|refreshed index from) .*255\.one/linux" \
        && ok "and it went to the real repository's LINUX channel -- installing the flagship package did not rewrite this machine's subscription" \
        || bad "the refresh did not name 255.one/linux: $(grep -a 'fetching channel' "$LOG" | head -1)"
    has '\[modupd\] p2 update status: 0' \
        && ok "a bare 'hpm update' exited 0" || bad "'hpm update' did not exit 0"
    has "hpm: upgrading $PKG $OLDVER -> $LIVEVER" \
        && ok "hpm named the upgrade $PKG $OLDVER -> $LIVEVER" \
        || bad "hpm did not name the $PKG upgrade"
    # THE MECHANISM: a package that is NEW in the channel arriving because the
    # version being upgraded to declares it.
    P2LIST="$(sect p2 LIST)"
    if printf '%s\n' "$P2LIST" | grep -qE "$DRVPKG[^0-9]*$DRVVER"; then
        ok "THE UPDATE PULLED IN A PACKAGE THAT DID NOT EXIST ON THIS MACHINE'S CHANNEL: $DRVPKG $DRVVER is now installed"
    else
        bad "$DRVPKG is NOT installed after the update. 'hpm update' upgrades installed packages, and a brand-new one only arrives as a dependency; nothing pulled it. THE 1.0.13 MODULES REACH NO UPDATING MACHINE."
    fi
    # THE BYTES, which no index field can satisfy.
    A="$(grep -aA1 -F "[modupd] p2 md5 of $KO after the update:" "$LOG" | tail -1 | tr -d '\r')"
    if printf '%s' "$A" | grep -q "$LIVE_KO_MD5"; then
        ok "$MOD.ko on the disk is the byte-for-byte published one ($LIVE_KO_MD5)"
    else
        bad "$MOD.ko on the disk is not the published bytes (got: $A)"
    fi
    B="$(grep -aA1 -F "[modupd] p2 md5 of $KODEP after the update:" "$LOG" | tail -1 | tr -d '\r')"
    if printf '%s' "$B" | grep -q "$LIVE_KODEP_MD5"; then
        ok "$DEPMOD_.ko on the disk is the byte-for-byte published one ($LIVE_KODEP_MD5)"
    else
        bad "$DEPMOD_.ko on the disk is not the published bytes (got: $B)"
    fi
fi
has '\[modupd\] PHASE2 DONE' && ok "phase 2 reached the end" || bad "phase 2 did not finish"

echo
echo "--- boot 3: THE SAME DISK. CAN IT LOAD A MODULE?"
LOG="$WORK/boot3.log"
has 'rc\.boot: hamnix-linux \(installed\)' \
    && ok "the machine booted again" || bad "the machine did not boot again"
P3LIST="$(sect p3 LIST)"
if [ "$NOUPD" != 1 ]; then
    printf '%s\n' "$P3LIST" | grep -qE "$DRVPKG[^0-9]*$DRVVER" \
        && ok "the new package survived the reboot ($DRVPKG $DRVVER)" \
        || bad "$DRVPKG is not installed after the reboot"
fi
# CAN THIS MACHINE TAKE THE *NEXT* UPDATE? A machine that has taken one and
# lost its subscription is a machine that will never take another, and nothing
# on it would say so.
P3CHAN="$(sect p3 CHANNELS)"
if printf '%s\n' "$P3CHAN" | grep -qx 'linux'; then
    ok "after the update the machine is still subscribed to the linux channel -- it can take the NEXT update too"
elif printf '%s\n' "$P3CHAN" | grep -qx 'main'; then
    bad "THE UPDATE REWROTE THIS MACHINE'S SUBSCRIPTION TO 'main'. That channel serves Hamnix NATIVE binaries and has no index.json.sig, so every future 'hpm refresh' on this machine aborts with a 404 and it can never take another update. The hpm package on the live channel ships etc/hpm/channels (the native list) at /etc/hpm/channels; the image stages etc/hpm/channels.linux there. Fixed in scripts/hamlinux_packages.py on this branch -- the live channel still carries the broken file and must be republished."
else
    bad "the machine's /etc/hpm/channels names no channel this gate recognises: $(printf '%s' "$P3CHAN" | tr '\n' '|')"
fi

P3BEFORE="$(sect p3 MODULES-BEFORE)"
for m in "$MOD" "$DEPMOD_" "$LATE"; do
    if inker "$P3BEFORE" "$m"; then
        bad "$m is in the kernel BEFORE modprobe runs -- something else loaded it and this proves nothing"
    else
        ok "$m is not in the kernel before modprobe runs on the updated machine"
    fi
done

# ===== QUESTION 1: THE MODULES ARRIVED AND THE NAME RESOLVES =====
P3LOAD="$(sect p3 LOAD)"
P3AFTER="$(sect p3 MODULES-AFTER)"
LORDER="$(printf '%s\n' "$P3LOAD" | sed -n 's/^modprobe: loaded \([a-z_0-9]*\) .*/\1/p' | tr '\n' ' ')"
say "modprobe $MOD loaded, in order: ${LORDER:-nothing}"
case "$LORDER" in
    "$DEPMOD_ $MOD "*) ok "loaded leaf-first: $DEPMOD_, then $MOD" ;;
    *) bad "load order was '${LORDER:-nothing}', not '$DEPMOD_ $MOD'" ;;
esac
for m in "$DEPMOD_" "$MOD"; do
    if inker "$P3AFTER" "$m"; then
        ok "$m IS IN THE KERNEL'S OWN LIST after the update: $(printf '%s\n' "$P3AFTER" | grep "^${m//-/_} " | head -1)"
    else
        bad "$m is NOT in /proc/modules -- an updated machine still cannot load it"
    fi
done
if printf '%s\n' "$P3AFTER" | grep -qE "^$DEPMOD_ .*$MOD"; then
    ok "the kernel records $MOD as a USER of $DEPMOD_ -- the dependency edge is real: $(printf '%s\n' "$P3AFTER" | grep "^$DEPMOD_ ")"
else
    bad "$DEPMOD_'s used-by column does not name $MOD; the dependency is not what was loaded"
fi

# ===== QUESTION 2: THE APPENDED DRIVER LINES SURVIVED =====
P3LATE="$(sect p3 LATE)"
LORDER2="$(printf '%s\n' "$P3LATE" | sed -n 's/^modprobe: loaded \([a-z_0-9]*\) .*/\1/p' | tr '\n' ' ')"
say "modprobe $LATE loaded, in order: ${LORDER2:-nothing}"
if printf '%s\n' "$P3LATE" | grep -q 'late status: 0'; then
    ok "modprobe $LATE exits 0 on the updated machine"
else
    bad "modprobe $LATE FAILED after the update: the machine keeps 8021q.ko on disk and has lost the only line that lets modprobe name it -- the appended driver lines did not survive. $(printf '%s\n' "$P3LATE" | grep -i 'modprobe:' | head -1)"
fi
for m in garp stp mrp llc "$LATE"; do
    if inker "$P3AFTER" "$m"; then
        ok "$m IS IN THE KERNEL'S OWN LIST: $(printf '%s\n' "$P3AFTER" | grep "^${m//-/_} " | head -1)"
    else
        bad "$m is not in /proc/modules after modprobe $LATE"
    fi
done

# ===== QUESTION 3: PREPEND, NOT REPLACE =====
P3TBL="$(sect p3 TABLE-BEFORE)"
FIRSTV="$(printf '%s\n' "$P3TBL" | grep "^kernel/fs/fat/$MOD\.ko:" | head -1)"
if [ -z "$FIRSTV" ]; then
    bad "the machine's table has no $MOD line at all after the update"
elif printf '%s' "$FIRSTV" | grep -q "$STALE"; then
    bad "the FIRST $MOD line is still the machine's stale one ($FIRSTV) -- the shipped table did not go in front, so modprobe resolves through a path that is not there"
else
    ok "the FIRST $MOD line is the shipped one, not the machine's stale one: $FIRSTV"
fi
if printf '%s\n' "$P3TBL" | grep -qF "$STALE"; then
    ok "and the machine's stale line is STILL IN THE TABLE, shadowed -- the shipped lines won by ORDER, which is what makes an appended driver line survivable"
else
    bad "the machine's own line is GONE: the package replaced the table instead of prepending it. Every line a driver package appended went with it."
fi
if printf '%s\n' "$P3TBL" | grep -qF "$LATE_LINE"; then
    ok "the driver-package line for $LATE is still in the table after the update"
else
    bad "the driver-package line for $LATE is gone from the table"
fi
has '\[modupd\] PHASE3 DONE' && ok "phase 3 reached the end" || bad "phase 3 did not finish"

echo
if [ "$DISK_SUM_BEFORE" = "$DISK_SUM_AFTER" ]; then
    bad "the disk is byte-identical before and after three boots -- nothing persisted"
else
    ok "the disk changed ($DISK_SUM_BEFORE -> $DISK_SUM_AFTER)"
fi
echo
echo "(live $PKG $LIVEVER, $DRVPKG $DRVVER; installed-at $OLDVER; kernel $KVER)"
echo "(logs: $WORK/boot1.log $WORK/boot2.log $WORK/boot3.log)"
echo "$PASS passed, $FAIL failed"
[ "$FAIL" = 0 ] || exit 1
