#!/usr/bin/env python3
# scripts/_bench_opt_gendoc.py — turn a bench_opt run log into docs/
# bench_opt_results.md. Parses the BENCH_OPT_MD block emitted by
# _bench_opt_run.py and renders the results table + headline ratios + the
# methodology/environment header. Invoked by scripts/bench_opt.sh.
import subprocess
import sys
from pathlib import Path


def cpu_model():
    try:
        for ln in Path("/proc/cpuinfo").read_text().splitlines():
            if ln.startswith("model name"):
                return ln.split(":", 1)[1].strip()
    except Exception:
        pass
    return "unknown"


def gcc_ver():
    try:
        return subprocess.run(["gcc", "--version"], capture_output=True,
                              text=True).stdout.splitlines()[0]
    except Exception:
        return "unknown"


def main():
    log_path, doc_path = sys.argv[1], sys.argv[2]
    lines = Path(log_path).read_text().splitlines()
    inblk = False
    reps = "?"
    rows = []
    miscompiles = []
    geomean = None
    for ln in lines:
        if ln.strip() == "=== BENCH_OPT_MD_BEGIN ===":
            inblk = True
            continue
        if ln.strip() == "=== BENCH_OPT_MD_END ===":
            inblk = False
            continue
        if not inblk:
            continue
        p = ln.split()
        if p[0] == "REPS":
            reps = p[1]
        elif p[0] == "ROW":
            # ROW name off on c0 c2 su rc2 rc0 checksum fired
            rows.append(p[1:])
        elif p[0] == "GEOMEAN":
            geomean = (p[1], p[2], p[3])
        elif p[0] == "MISCOMPILE":
            miscompiles.append(p[1:])

    out = []
    out.append("# Adder optimizer performance benchmark — 4-way comparison")
    out.append("")
    out.append("Auto-generated by `bash scripts/bench_opt.sh` "
               "(`scripts/_bench_opt_run.py`). Re-run to refresh.")
    out.append("")
    out.append("## What is compared")
    out.append("")
    out.append("Four configurations on identical compute kernels "
               "(`tests/bench/opt/<name>.{ad,c}`):")
    out.append("")
    out.append("1. **Adder, optimizer OFF** — native `codegen.ad`, no `--opt` "
               "(baseline stack-machine backend).")
    out.append("2. **Adder, optimizer ON** — native `codegen.ad` with `--opt` "
               "/ `ADDER_OPT=1`: the 6-pass optimizer (const-fold, CSE, LICM, "
               "DCE, constant-condition branch-fold, copy-propagation).")
    out.append("3. **C, gcc -O0** — unoptimized C.")
    out.append("4. **C, gcc -O2** — optimized C.")
    out.append("")
    out.append("## Methodology — why it is fair")
    out.append("")
    out.append("The native Adder compiler's `x86_64-linux` host path "
               "(`tests/fuzz/ad_codegen_host.py`) runs lex → parse → opt → "
               "`codegen.ad` and **wraps the emitted machine code into a real "
               "`ELF64` `EM_X86_64` executable** that runs natively on this "
               "host CPU — the *same CPU* and *same ELF ABI* as the "
               "gcc-compiled C binaries. All four configs are therefore timed "
               "as ordinary host processes on one CPU: no QEMU, no Hamnix "
               "image, no cross-VM timer skew. The only difference between (1) "
               "and (2) is whether `opt.ad`'s passes ran; between Adder and C, "
               "only the compiler. (The C binaries are timed on the host rather "
               "than inside an `enter linux {}` namespace for exactly this "
               "reason — keeping every config on one bare CPU is the fairest "
               "control.)")
    out.append("")
    out.append("**Correctness before speed.** Each kernel prints one decimal "
               "checksum; the harness asserts it is *identical* across all four "
               "builds before timing any of them. The Adder-OFF and both C "
               "builds must agree (that pins the reference answer); a kernel "
               "whose `ADDER_OPT=1` build disagrees is reported as a "
               "**miscompile finding** and excluded from the speed table — a "
               "fast wrong answer is not a benchmark.")
    out.append("")
    out.append(f"**Noise control.** Each binary is warmed up once (discarded), "
               f"then timed **best-of-{reps}** (minimum wall time). Iteration "
               "counts are sized so every kernel runs well over 100 ms even at "
               "C -O2, dwarfing process-spawn + timer overhead. The kernels "
               "that are pure ALU/closed-form (`licm`, `dcecopy`) write into a "
               "global ring buffer each step so gcc -O2 cannot delete the loop "
               "— the comparison stays about generated loop code, not gcc's "
               "loop-elimination.")
    out.append("")
    out.append("## Environment")
    out.append("")
    out.append(f"- **CPU:** {cpu_model()}")
    out.append(f"- **C compiler:** {gcc_ver()}")
    out.append(f"- **Reps:** best-of-{reps}, after 1 warm-up")
    out.append("- **Adder compiler:** native `codegen.ad` via the "
               "`x86_64-linux` host wrapper (`tests/fuzz/ad_codegen_host.py`)")
    out.append("")
    out.append("## Results")
    out.append("")
    out.append("Timings in seconds (best-of-N, lower is better). "
               "`ON/OFF` > 1 means the optimizer made Adder *faster*; "
               "`ON/C-O2` and `ON/C-O0` are how many times *slower* "
               "Adder-ON is than C.")
    out.append("")
    out.append("| kernel | Adder-OFF | Adder-ON | C-O0 | C-O2 | "
               "ON/OFF (speedup) | ON / C-O2 | ON / C-O0 | opt passes fired |")
    out.append("|---|--:|--:|--:|--:|--:|--:|--:|---|")
    for r in rows:
        name, off, on, c0, c2, su, rc2, rc0, chk, fired = r
        fired_md = fired.replace(";", ", ") if fired != "none" else "—"
        out.append(f"| {name} | {off}s | {on}s | {c0}s | {c2}s | "
                   f"**{su}×** | {rc2}× | {rc0}× | {fired_md} |")
    if geomean:
        out.append(f"| **geomean** | | | | | **{geomean[0]}×** | "
                   f"{geomean[1]}× | {geomean[2]}× | |")
    out.append("")
    if geomean:
        out.append("## Headline")
        out.append("")
        out.append(f"- **Optimizer ON vs OFF:** the `ADDER_OPT=1` 6-pass "
                   f"optimizer is **{geomean[0]}× faster** than the baseline "
                   f"backend (geomean over the correct kernels).")
        out.append(f"- **Adder-ON vs C -O2:** Adder-ON is **{geomean[1]}× "
                   f"slower** than gcc -O2 (geomean).")
        out.append(f"- **Adder-ON vs C -O0:** Adder-ON is **{geomean[2]}× "
                   f"slower** than gcc -O0 (geomean).")
        out.append("")
    if miscompiles:
        out.append("## Correctness finding — `ADDER_OPT=1` miscompiles")
        out.append("")
        out.append("The following kernels produce the WRONG checksum under "
                   "`ADDER_OPT=1` (optimizer ON) and are **excluded from the "
                   "speed table**. The Adder-OFF baseline and both C builds all "
                   "agree on the reference value, so this is an optimizer bug, "
                   "not a bad kernel. Per the benchmark's rules the optimizer "
                   "was **not** modified to hide this.")
        out.append("")
        out.append("| kernel | reference checksum | ADDER_OPT=1 got |")
        out.append("|---|--:|--:|")
        for m in miscompiles:
            # MISCOMPILE name ref=.. adder_opt1_got=..
            name = m[0]
            ref = m[1].split("=", 1)[1]
            got = m[2].split("=", 1)[1]
            out.append(f"| {name} | {ref} | {got} |")
        out.append("")
        out.append("**Shape of the bug (minimal repro).** All three failing "
                   "kernels share one control-flow shape: a `while` loop "
                   "nested inside an outer loop, where a local accumulator is "
                   "re-initialised at the top of each outer iteration and read "
                   "*after* the inner loop. Minimal trigger:")
        out.append("")
        out.append("```")
        out.append("def main(argc: int32, argv: Ptr[uint64]) -> int32:")
        out.append("    acc: int64 = 0")
        out.append("    reps: int64 = 0")
        out.append("    while reps < 3:")
        out.append("        count: int64 = 0          # re-init each outer pass")
        out.append("        i: int64 = 0")
        out.append("        while i < 5:")
        out.append("            count = count + 1")
        out.append("            i = i + 1")
        out.append("        acc = acc + count         # read after inner loop")
        out.append("        reps = reps + 1")
        out.append("    print_u64(cast[uint64](acc))  # OFF: 15   ON: 6  (WRONG)")
        out.append("    return cast[int32](0)")
        out.append("```")
        out.append("")
        out.append("Expected `15` (3 × 5); `ADDER_OPT=1` emits `6`. The "
                   "optimizer drops all but the last outer pass's contribution "
                   "(the per-pass re-init of `count` is mishandled). None of "
                   "the six pass counters fire on this unit, so the defect is "
                   "in the IR-emit/lowering path the `--opt` mode enables, not "
                   "in a high-level pass. This evades the predicted-output "
                   "fuzzer (which reports 0 miscompiles) because the fuzzer's "
                   "generated corpus does not exercise this nested-loop "
                   "reset-and-read shape.")
        out.append("")
    Path(doc_path).write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
