# scripts/_kernel_iso.sh — boot the higher-half Hamnix kernel under QEMU.
#
# WHY THIS EXISTS
#
# The Hamnix kernel is now a HIGHER-HALF kernel: a true elf64-x86-64
# ELF linked at 0xffffffff80000000 (see arch/x86/kernel/vmlinux.lds).
# QEMU's built-in `-kernel` multiboot1 loader REJECTS 64-bit ELFs
# outright ("Cannot load x86-64 image, give a 32bit one") — it only
# accepts ELFCLASS32. GRUB's multiboot1 ELF loader, by contrast,
# happily loads ELFCLASS64 and honours the program headers' 64-bit
# p_paddr fields, which is exactly what the kernel's VMA/LMA split
# needs.
#
# The Hamnix test suite has ~270 scripts that boot the bare-metal
# kernel with `qemu-system-x86_64 ... -kernel "$ELF" ...` — very often
# as `timeout <dur> qemu-system-x86_64 ...`. A shell-function shim
# can't intercept the `timeout`-wrapped form (`timeout` execs its
# argument as a real binary, bypassing shell functions). So instead
# this file installs a REAL EXECUTABLE shim named `qemu-system-x86_64`
# into build/binshim/ and PREPENDS that directory to PATH. Every
# `qemu-system-x86_64` invocation — direct or `timeout`-wrapped —
# then resolves to the shim, which:
#   - if a `-kernel <file>` arg names an ELFCLASS64 ELF (the Hamnix
#     higher-half kernel), wraps it in a BIOS GRUB ISO and execs the
#     real QEMU with `-cdrom <iso>` swapped in for `-kernel <file>`;
#   - otherwise (a real Linux bzImage, or a `-cdrom`/`-bios` boot)
#     execs the real QEMU with the arguments untouched.
#
# This file is sourced by scripts/_build_lock.sh (which every test
# script sources first) and by the couple of scripts that don't go
# through _build_lock.sh.
#
# USAGE (the function form, for callers that want an ISO explicitly)
#
#   . "$(dirname "$0")/_kernel_iso.sh"
#   iso=$(kernel_iso /path/to/hamnix-vmlinux.elf)
#   qemu-system-x86_64 -cdrom "$iso" ...

# kernel_iso <kernel-elf> [iso-out]
#   Build a minimal BIOS GRUB ISO that multiboot-loads <kernel-elf>.
#   Echoes the ISO path. iso-out defaults to <kernel-elf>.iso.
kernel_iso() {
    local kelf="$1"
    local iso_out="${2:-${kelf}.iso}"

    if [ ! -f "$kelf" ]; then
        echo "[kernel_iso] ERROR: kernel ELF not found: $kelf" >&2
        return 1
    fi
    if ! command -v grub-mkrescue >/dev/null 2>&1; then
        echo "[kernel_iso] ERROR: grub-mkrescue not found (apt install grub-pc-bin grub-common xorriso)" >&2
        return 1
    fi

    local stage
    stage="$(mktemp -d)"
    mkdir -p "$stage/boot/grub"
    cp "$kelf" "$stage/boot/hamnix.elf"
    # timeout=0 → boot immediately, no menu wait (tests are headless).
    cat > "$stage/boot/grub/grub.cfg" <<'GRUB_CFG_EOF'
set timeout=0
set default=0
menuentry "Hamnix" {
    multiboot /boot/hamnix.elf
    boot
}
GRUB_CFG_EOF

    rm -f "$iso_out"
    # BIOS-only ISO (grub-pc). No UEFI re-master needed — these are
    # QEMU SeaBIOS test boots. grub-mkrescue emits the El Torito
    # i386-pc record + hybrid MBR; QEMU `-cdrom` boots it directly.
    if ! grub-mkrescue -o "$iso_out" "$stage" >/dev/null 2>&1; then
        echo "[kernel_iso] ERROR: grub-mkrescue failed for $kelf" >&2
        rm -rf "$stage"
        return 1
    fi
    rm -rf "$stage"
    if [ ! -f "$iso_out" ]; then
        echo "[kernel_iso] ERROR: ISO not produced: $iso_out" >&2
        return 1
    fi
    echo "$iso_out"
}

# _install_qemu_shim — write build/binshim/qemu-system-x86_64 and
# prepend build/binshim to PATH. Idempotent: safe to source many times.
_install_qemu_shim() {
    local proj_root shim_dir shim
    proj_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    shim_dir="$proj_root/build/binshim"
    shim="$shim_dir/qemu-system-x86_64"

    mkdir -p "$shim_dir"

    # (Re)write the shim. It's tiny; rewriting each source keeps it in
    # sync if this file changes, and avoids a stale-shim hazard.
    cat > "$shim" <<'SHIM_EOF'
#!/usr/bin/env bash
# build/binshim/qemu-system-x86_64 — AUTOGENERATED by scripts/_kernel_iso.sh.
#
# Transparent boot shim for the higher-half Hamnix kernel. QEMU's
# `-kernel` multiboot1 loader rejects 64-bit ELFs; GRUB's does not. If
# this shim is asked to `-kernel` an ELFCLASS64 file, it wraps that
# file in a BIOS GRUB ISO and execs the real QEMU with `-cdrom <iso>`.
# Any other invocation is passed straight through. Do not edit — edit
# scripts/_kernel_iso.sh instead.
#
# HARDWARE ACCELERATION
#
# Every Hamnix QEMU invocation routes through this shim (it is named
# `qemu-system-x86_64` and prepended to PATH). So this is the ONE place
# the accelerator is chosen. Pure-TCG software emulation is ~10-50x
# slower than KVM and, with several worktree-isolated test agents
# running concurrently, thrashes the box. When `/dev/kvm` is readable
# AND writable by the current user the shim injects `-accel kvm` (plus
# `-cpu host` if the caller did not pick a CPU model). On a host with
# no usable `/dev/kvm` (CI runners, KVM-less environments) nothing is
# injected and QEMU keeps its default TCG accelerator — the fallback
# stays fully functional. The injection is suppressed if the caller
# already chose an accelerator (`-accel`, `-enable-kvm`, or
# `-machine ...accel=`), so explicit overrides always win.
#
# GLOBAL (CROSS-WORKTREE) CONCURRENCY CAP
#
# scripts/_build_lock.sh only serialises builds WITHIN one worktree.
# Several agents in separate worktrees can each spawn QEMU at once and
# thrash a 12-core box. Because every QEMU invocation funnels through
# this shim, the shim is also the natural place for a global limiter:
# before exec'ing the real QEMU it grabs one of N flock slots under a
# fixed absolute path (HAMNIX_QEMU_SLOT_DIR, default /tmp/hamnix-qemu-
# slots). The flock fd is inherited across `exec` and auto-released
# when QEMU exits, so the *total* number of concurrent QEMU processes
# across ALL worktrees is capped at N (default: ncores/2). Set
# HAMNIX_QEMU_SLOTS=0 to disable the cap.
set -euo pipefail

# Find the REAL qemu-system-x86_64, skipping this shim's own directory.
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REAL_QEMU=""
for cand in /usr/bin/qemu-system-x86_64 /usr/local/bin/qemu-system-x86_64; do
    if [ -x "$cand" ]; then REAL_QEMU="$cand"; break; fi
done
if [ -z "$REAL_QEMU" ]; then
    # Fall back to a PATH search that excludes our own dir.
    _ifs="$IFS"; IFS=:
    for d in $PATH; do
        [ "$d" = "$SELF_DIR" ] && continue
        if [ -x "$d/qemu-system-x86_64" ]; then
            REAL_QEMU="$d/qemu-system-x86_64"; break
        fi
    done
    IFS="$_ifs"
fi
if [ -z "$REAL_QEMU" ]; then
    echo "[qemu-shim] ERROR: real qemu-system-x86_64 not found" >&2
    exit 127
fi

# qemu_exec — acquire a global concurrency slot, then exec the real
# QEMU with the given argv. The flock fd survives `exec` and is held
# for QEMU's whole lifetime; the kernel releases it when QEMU exits.
# That makes the slot dir a counting semaphore shared by every agent
# worktree. If all slots stay busy past the backstop, or the cap is
# disabled / unusable, we exec anyway — correctness must not depend on
# the limiter, it only smooths load.
qemu_exec() {
    local slots slot_dir
    slots="${HAMNIX_QEMU_SLOTS:-}"
    if [ -z "$slots" ]; then
        # Default cap: ncores/2, floored at 1.
        local nc
        nc="$(nproc 2>/dev/null || echo 4)"
        slots=$(( nc / 2 ))
        [ "$slots" -lt 1 ] && slots=1
    fi
    slot_dir="${HAMNIX_QEMU_SLOT_DIR:-/tmp/hamnix-qemu-slots}"

    if [ "$slots" -gt 0 ] && command -v flock >/dev/null 2>&1 \
       && mkdir -p "$slot_dir" 2>/dev/null; then
        # Pre-create the slot files so the fd-8 open below cannot fail.
        local s
        for (( s=1; s<=slots; s++ )); do
            : >> "$slot_dir/slot.$s" 2>/dev/null || true
        done
        # Backstop: don't wait forever — a crashed holder must not
        # wedge the suite. ~10 min is well past the slowest test.
        local deadline=$(( SECONDS + 600 ))
        while :; do
            for (( s=1; s<=slots; s++ )); do
                # fd 8 carries the slot lock into the exec'd QEMU; the
                # kernel drops it when QEMU exits. Reopening fd 8 onto
                # the next slot file releases any prior (failed) lock.
                exec 8>>"$slot_dir/slot.$s"
                if flock -n 8; then
                    exec "$REAL_QEMU" "$@"
                fi
            done
            if [ "$SECONDS" -ge "$deadline" ]; then
                echo "[qemu-shim] WARN: no QEMU slot free after 600s;" \
                     "running uncapped" >&2
                break
            fi
            sleep 0.5
        done
    fi
    # Cap disabled or unavailable: exec uncapped.
    exec "$REAL_QEMU" "$@"
}

# Locate a `-kernel <file>` pair and an optional `-append <cmdline>`.
# A GRUB ISO boot has no `-kernel`/`-append`; the kernel command line
# (if any) goes on the grub.cfg `multiboot` line, and QEMU rejects a
# bare `-append` without `-kernel`. So we capture both and drop them.
# Also note whether the caller already set `-boot`, picked a CPU model
# (`-cpu`), or chose an accelerator (`-accel`/`-enable-kvm`/`-machine
# accel=`).
KELF=""
KAPPEND=""
HAS_BOOT=0
HAS_CPU=0
HAS_ACCEL=0
args=("$@")
n=$#
for (( i=0; i<n; i++ )); do
    if [ "${args[$i]}" = "-kernel" ] && [ $((i+1)) -lt "$n" ]; then
        KELF="${args[$((i+1))]}"
    elif [ "${args[$i]}" = "-append" ] && [ $((i+1)) -lt "$n" ]; then
        KAPPEND="${args[$((i+1))]}"
    elif [ "${args[$i]}" = "-boot" ]; then
        HAS_BOOT=1
    elif [ "${args[$i]}" = "-cpu" ]; then
        HAS_CPU=1
    elif [ "${args[$i]}" = "-accel" ] || [ "${args[$i]}" = "-enable-kvm" ]; then
        HAS_ACCEL=1
    elif [ "${args[$i]}" = "-machine" ] || [ "${args[$i]}" = "-M" ]; then
        case "${args[$((i+1))]:-}" in *accel=*) HAS_ACCEL=1 ;; esac
    fi
done

# --- accelerator selection ------------------------------------------
# Inject `-accel kvm` (the ~10-50x speedup over TCG) when the host has
# a usable /dev/kvm and the caller did not already pick an accelerator.
# `-cpu host` exposes the bare-metal CPU to the guest, but it is only
# valid under a hardware accelerator — add it only when we are turning
# KVM on AND the caller did not already choose a `-cpu` model. With no
# usable /dev/kvm, ACCEL_ARGS stays empty and QEMU keeps its default
# TCG accelerator, so KVM-less hosts (CI) still work unchanged.
# HAMNIX_QEMU_NO_KVM=1 forces the TCG fallback even when /dev/kvm is
# usable — handy for reproducing CI behaviour or A/B timing.
ACCEL_ARGS=()
if [ "$HAS_ACCEL" -eq 0 ] && [ "${HAMNIX_QEMU_NO_KVM:-0}" != "1" ]; then
    if [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
        ACCEL_ARGS+=("-accel" "kvm")
        if [ "$HAS_CPU" -eq 0 ]; then
            ACCEL_ARGS+=("-cpu" "host")
        fi
    fi
fi

# Pass through unchanged unless -kernel names an ELFCLASS64 ELF.
is_elf64=0
if [ -n "$KELF" ] && [ -f "$KELF" ]; then
    if head -c 5 "$KELF" 2>/dev/null | od -An -tx1 2>/dev/null \
         | grep -q '7f 45 4c 46 02'; then
        is_elf64=1
    fi
fi
if [ "$is_elf64" -ne 1 ]; then
    # Pass-through boot (real Linux bzImage, or a `-cdrom`/`-bios` ISO
    # boot such as test_bios_boot / test_uefi_boot / test_iso_qemu).
    # Still inject the accelerator so these paths get KVM too.
    qemu_exec "${ACCEL_ARGS[@]}" "$@"
fi

# Wrap the ELFCLASS64 Hamnix kernel in a BIOS GRUB ISO. Any `-append`
# command line rides on the grub.cfg `multiboot` line.
KISO="${KELF}.iso"
STAGE="$(mktemp -d)"
mkdir -p "$STAGE/boot/grub"
cp "$KELF" "$STAGE/boot/hamnix.elf"
{
    echo "set timeout=0"
    echo "set default=0"
    echo 'menuentry "Hamnix" {'
    if [ -n "$KAPPEND" ]; then
        echo "    multiboot /boot/hamnix.elf $KAPPEND"
    else
        echo "    multiboot /boot/hamnix.elf"
    fi
    echo "    boot"
    echo "}"
} > "$STAGE/boot/grub/grub.cfg"
rm -f "$KISO"
if ! grub-mkrescue -o "$KISO" "$STAGE" >/dev/null 2>&1; then
    echo "[qemu-shim] ERROR: grub-mkrescue failed for $KELF" >&2
    rm -rf "$STAGE"
    exit 2
fi
rm -rf "$STAGE"

# Swap `-kernel <elf>` for `-cdrom <iso>` and drop `-append <cmdline>`
# (folded into grub.cfg above).
out=()
for (( i=0; i<n; i++ )); do
    if [ "${args[$i]}" = "-kernel" ]; then
        out+=("-cdrom" "$KISO")
        i=$((i+1))           # skip the kernel-file argument
    elif [ "${args[$i]}" = "-append" ]; then
        i=$((i+1))           # skip -append and its cmdline argument
    else
        out+=("${args[$i]}")
    fi
done

# Force CD-ROM-first boot order. With `qemu -kernel` QEMU loaded the
# kernel directly and SeaBIOS' boot-device selection never ran. Now
# that we boot from a `-cdrom` ISO, SeaBIOS DOES enumerate boot
# devices — and a test that also attaches a data disk carrying an MBR
# signature (test_ahci / test_nvme mint a `\x55\xaa`-stamped disk)
# would otherwise see SeaBIOS pick that non-bootable hard disk first
# and hang at "Booting from Hard Disk...". `-boot d` pins the CD
# first. Added only when the caller didn't already specify `-boot`.
if [ "$HAS_BOOT" -eq 0 ]; then
    out+=("-boot" "d")
fi
qemu_exec "${ACCEL_ARGS[@]}" "${out[@]}"
SHIM_EOF
    chmod +x "$shim"

    # Prepend the shim dir to PATH (once).
    case ":$PATH:" in
        *":$shim_dir:"*) : ;;          # already present
        *) export PATH="$shim_dir:$PATH" ;;
    esac
}

_install_qemu_shim
