#!/usr/bin/env python3
"""
scripts/build_diskimg.py — generates a raw disk image and emits it
as fs/diskimg_blob.S of .byte directives that the kernel image
.incbin-includes. Mirrors scripts/build_initramfs.py for the cpio
archive.

M16.42 ships with a synthetic 16-sector (8 KiB) image whose layout
is:

  sector 0  : 0x55 0xAA repeated to 512 bytes (boot-sig magic
              so the block-layer smoke test can spot it)
  sector 1..7: zero
  sector 8  : "HAMNIXFS" + zero-pad — second magic the smoke test
              reads to prove non-zero LBA addressing works
  sector 9..15: zero

Future milestones (M16.43+) will replace this with a real FAT32
image produced by `mkfs.fat`. The build_user.sh / kernel build
chain stays the same; only the contents change.
"""

from pathlib import Path

SECTOR_SIZE = 512
N_SECTORS   = 16


def build_image() -> bytes:
    buf = bytearray(N_SECTORS * SECTOR_SIZE)
    # Sector 0: alternating 0x55 / 0xAA (the legacy MBR boot
    # signature pattern, just used as an identifiable byte pattern
    # for the smoke test — we're not booting from sector 0).
    for i in range(SECTOR_SIZE):
        buf[i] = 0x55 if (i % 2 == 0) else 0xAA
    # Sector 8: 8-byte ASCII tag at the head.
    tag = b"HAMNIXFS"
    off = 8 * SECTOR_SIZE
    buf[off:off + len(tag)] = tag
    return bytes(buf)


def emit_asm(image: bytes, dest: Path) -> None:
    lines = [
        "/* AUTOGENERATED by scripts/build_diskimg.py — do not edit. */",
        "    .section .rodata",
        "    .align 8",
        "    .globl diskimg_start",
        "diskimg_start:",
    ]
    for i in range(0, len(image), 16):
        chunk = image[i:i + 16]
        bytes_csv = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    .byte {bytes_csv}")
    lines += [
        "    .globl diskimg_end",
        "diskimg_end:",
        "",
        "    .code64",
        "    .section .text, \"ax\"",
        # uint64 diskimg_base(): returns the start address.
        "    .globl diskimg_base",
        "diskimg_base:",
        "    leaq diskimg_start(%rip), %rax",
        "    ret",
        # uint64 diskimg_size(): returns end - start.
        "    .globl diskimg_size",
        "diskimg_size:",
        "    leaq diskimg_end(%rip), %rax",
        "    leaq diskimg_start(%rip), %rcx",
        "    subq %rcx, %rax",
        "    ret",
    ]
    dest.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    here = Path(__file__).resolve().parent.parent
    image = build_image()
    dest = here / "fs" / "diskimg_blob.S"
    emit_asm(image, dest)
    print(f"Wrote {dest} ({len(image)} bytes image, "
          f"{N_SECTORS} sectors of {SECTOR_SIZE})")
