#!/usr/bin/env bash
# scripts/framediff_gfx_all.sh — run the whole PIXEL browser-fidelity corpus and
# publish the CANONICAL Chrome/Firefox parity scorecard (docs/browser_framediff.md).
#
# For every page under tests/framediff/pages/*.html it invokes
# scripts/framediff_gfx_run.sh (hambrowse PIXEL render vs headless chromium AND
# firefox), collects each page's SSIM + blurred-RMSE + raw RMSE, and writes a
# summary table ranked worst-first by structural distance (1 - mean SSIM — the
# biggest real Chrome/Firefox gaps to close). SSIM is the primary signal because
# raw RMSE over-penalizes correct large text (area + subpixel AA). Diff /
# side-by-side PNGs land under build/framediff_gfx/<page>/ (ephemeral).
#
# USAGE
#   scripts/framediff_gfx_all.sh [width]
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

WIDTH="${1:-800}"
CORPUS="tests/framediff/pages"
DOC="docs/browser_framediff.md"
RESULTS="build/framediff_gfx"
mkdir -p "$RESULTS" docs

# force a clean pixel-backend build so the table reflects the current engine
rm -f build/host/hambrowse_gfx

pages=("$CORPUS"/*.html)
[ -e "${pages[0]}" ] || { echo "[framediff-gfx-all] no corpus pages under $CORPUS"; exit 1; }

declare -A NORM_CHR NORM_FF RM_CHR RM_FF SSIM_CHR SSIM_FF BRMSE_CHR BRMSE_FF
for page in "${pages[@]}"; do
    name="$(basename "$page" .html)"
    echo "==== $name ===="
    bash scripts/framediff_gfx_run.sh "$page" "$WIDTH" || echo "[framediff-gfx-all] $name had no references"
    sc="$RESULTS/$name/score.txt"
    if [ -f "$sc" ]; then
        # score.txt: engine rmse rmse_norm ae ssim brmse dssim
        while read -r eng rmse norm ae ssim brmse dssim; do
            case "$eng" in
                chromium) RM_CHR[$name]="$rmse"; NORM_CHR[$name]="$norm"
                          SSIM_CHR[$name]="$ssim"; BRMSE_CHR[$name]="$brmse" ;;
                firefox)  RM_FF[$name]="$rmse";  NORM_FF[$name]="$norm"
                          SSIM_FF[$name]="$ssim"; BRMSE_FF[$name]="$brmse" ;;
            esac
        done <"$sc"
    fi
done

# ---- rank pages by mean structural DISSIMILARITY (worst first) ---------------
# We rank by SSIM-based distance (1 - mean SSIM), NOT raw RMSE: raw RMSE mis-ranks
# a structurally-correct large render below a mono blob (it over-weights area +
# subpixel AA). The worst-SSIM pages are the real Chrome/Firefox gaps to close.
ranked="$(for page in "${pages[@]}"; do
    name="$(basename "$page" .html)"
    sc="${SSIM_CHR[$name]:-}"; sf="${SSIM_FF[$name]:-}"
    dist="$(awk -v a="$sc" -v b="$sf" 'BEGIN{
        n=0; s=0; if(a!=""&&a!="n/a"){s+=a;n++} if(b!=""&&b!="n/a"){s+=b;n++}
        if(n==0){print "999"} else {printf "%.6f", 1.0 - s/n} }')"
    printf '%s\t%s\n' "$dist" "$name"
done | sort -rn)"

# ---- write the canonical parity scorecard ------------------------------------
ts="$(date -u +%Y-%m-%dT%H:%MZ)"
{
    echo "# Browser fidelity harness (framediff — pixel)"
    echo
    echo "_Auto-generated by \`scripts/framediff_gfx_all.sh\` — last run ${ts},"
    echo "viewport width ${WIDTH}px._"
    echo
    echo "This is the **canonical Chrome/Firefox parity scorecard**. Each page is"
    echo "rendered by the native hambrowse PIXEL backend (\`user/hambrowse_host_gfx.ad\`"
    echo "-> \`lib/htmlpage\`+\`lib/htmlpaint\`, the SAME layout+paint code that runs on"
    echo "device, with PROPORTIONAL TrueType text + a real heading hierarchy + the"
    echo "engine's proportional line-reflow), by headless **chromium**, and by headless"
    echo "**firefox**. Geometry is normalized (flatten-white, content-bbox trim, resize"
    echo "reference to the hambrowse content box)."
    echo
    echo "## The metric"
    echo
    echo "**SSIM is the primary parity signal** (structural similarity, 0..1, HIGHER =="
    echo "closer). Raw full-frame RMSE is a poor renderer metric: it area-scales (a big,"
    echo "*correct* heading accumulates more absolute AA error than a tiny wrong render)"
    echo "and it treats every subpixel-misregistered antialiased edge as a full error."
    echo "Historically raw RMSE *rose* when headings started rendering at true size —"
    echo "punishing the fidelity gain. **SSIM** and the downsample+blur **brmse** (0..1,"
    echo "LOWER = closer) both reward STRUCTURE (right boxes, right text at the right"
    echo "place & size) and tolerate the AA/hinting/baseline differences a reader does"
    echo "not care about. Raw RMSE stays as a continuity column only. See"
    echo "\`scripts/framediff_metric.py\`. Pages are ranked worst-first by \`1 - meanSSIM\`."
    echo
    echo "| Rank | Page | SSIM vs chromium ↑ | SSIM vs firefox ↑ | brmse chr ↓ | brmse ff ↓ | RMSE chr (norm) | RMSE ff (norm) |"
    echo "|-----:|------|-------------------:|------------------:|------------:|-----------:|----------------:|---------------:|"
    rank=0
    while IFS=$'\t' read -r dist name; do
        rank=$((rank+1))
        sc="${SSIM_CHR[$name]:-n/a}"; sf="${SSIM_FF[$name]:-n/a}"
        bc="${BRMSE_CHR[$name]:-n/a}"; bf="${BRMSE_FF[$name]:-n/a}"
        c="${RM_CHR[$name]:-n/a}"; cn="${NORM_CHR[$name]:-}"
        f="${RM_FF[$name]:-n/a}"; fn="${NORM_FF[$name]:-}"
        [ -n "$cn" ] && c="$c ($cn)"
        [ -n "$fn" ] && f="$f ($fn)"
        printf '| %d | %s | %s | %s | %s | %s | %s | %s |\n' \
            "$rank" "$name" "$sc" "$sf" "$bc" "$bf" "$c" "$f"
    done <<<"$ranked"
    echo
    echo "Per-page artifacts (hambrowse-pixel | reference | heatmap):"
    echo
    for page in "${pages[@]}"; do
        name="$(basename "$page" .html)"
        echo "- \`$name\`: \`$RESULTS/$name/sxs_chromium.png\`, \`$RESULTS/$name/sxs_firefox.png\`, \`$RESULTS/$name/diff_chromium.png\`"
    done
    echo
    echo "Regenerate: \`scripts/framediff_gfx_all.sh $WIDTH\`. Single page:"
    echo "\`scripts/framediff_gfx_run.sh $CORPUS/<name>.html $WIDTH\`. A quick text-mode"
    echo "(mono-grid) preview of the engine's display list lives in"
    echo "\`docs/browser_framediff_textmode.md\` (\`scripts/framediff_all.sh\`) — that path"
    echo "reads the char-grid dump and is NOT a parity signal; use this doc for parity."
} >"$DOC"

echo "[framediff-gfx-all] wrote $DOC and $RESULTS/*/"
echo "== ranked (worst structural first) =="
echo "$ranked"
