#!/usr/bin/env bash
# scripts/framediff_all.sh — run the whole browser-fidelity corpus and publish
# the DEV METRIC the browser team iterates against.
#
# For every page under tests/framediff/pages/*.html it invokes
# scripts/framediff_run.sh (hambrowse host render-to-PNG vs headless
# chromium/firefox), collects each page's RMSE-vs-reference, and writes a legible
# summary table (lower == closer) plus the results-dir paths into
# docs/browser_framediff.md. Diff/side-by-side PNGs land under
# build/framediff/<page>/ (ephemeral; regenerate with this script).
#
# USAGE
#   scripts/framediff_all.sh [width]
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

WIDTH="${1:-800}"
CORPUS="tests/framediff/pages"
DOC="docs/browser_framediff.md"
RESULTS="build/framediff"
mkdir -p "$RESULTS" docs

# force a clean host-harness build so the table reflects current engine
rm -f build/host/hambrowse_host

pages=("$CORPUS"/*.html)
[ -e "${pages[0]}" ] || { echo "[framediff-all] no corpus pages under $CORPUS"; exit 1; }

declare -A RM_CHR RM_FF NORM_CHR NORM_FF
for page in "${pages[@]}"; do
    name="$(basename "$page" .html)"
    echo "==== $name ===="
    bash scripts/framediff_run.sh "$page" "$WIDTH" || echo "[framediff-all] $name had no references"
    sc="$RESULTS/$name/score.txt"
    if [ -f "$sc" ]; then
        while read -r eng rmse norm ae; do
            case "$eng" in
                chromium) RM_CHR[$name]="$rmse"; NORM_CHR[$name]="$norm" ;;
                firefox)  RM_FF[$name]="$rmse";  NORM_FF[$name]="$norm" ;;
            esac
        done <"$sc"
    fi
done

# ---- render the summary table into the doc -----------------------------------
ts="$(date -u +%Y-%m-%dT%H:%MZ)"
{
    echo "# Browser fidelity harness (framediff)"
    echo
    echo "_Auto-generated by \`scripts/framediff_all.sh\` — last run ${ts}, viewport width ${WIDTH}px._"
    echo
    echo "This is a **relative dev metric**, not a pixel-parity claim. Each page is"
    echo "rendered by the native hambrowse engine (host render-to-PNG dual target),"
    echo "by headless **chromium**, and by headless **firefox**; geometry is"
    echo "normalized (chrome stripped, reference resized to the hambrowse content"
    echo "box) and scored with ImageMagick \`compare\`. **Lower RMSE == closer to the"
    echo "reference.** RMSE is on ImageMagick's 0..65535 scale; the parenthesised"
    echo "value is the 0..1 normalized form. See the *Reading the score* and"
    echo "*Harness artifacts vs real gaps* sections below before trusting a number."
    echo
    echo "| Page | RMSE vs chromium | RMSE vs firefox |"
    echo "|------|-----------------:|----------------:|"
    for page in "${pages[@]}"; do
        name="$(basename "$page" .html)"
        c="${RM_CHR[$name]:-n/a}"; cn="${NORM_CHR[$name]:-}"
        f="${RM_FF[$name]:-n/a}"; fn="${NORM_FF[$name]:-}"
        [ -n "$cn" ] && c="$c ($cn)"
        [ -n "$fn" ] && f="$f ($fn)"
        printf '| %s | %s | %s |\n' "$name" "$c" "$f"
    done
    echo
    echo "Side-by-side (hambrowse | reference | heatmap) and heatmap PNGs per page:"
    echo
    for page in "${pages[@]}"; do
        name="$(basename "$page" .html)"
        echo "- \`$name\`: \`$RESULTS/$name/sxs_chromium.png\`, \`$RESULTS/$name/diff_chromium.png\` (regenerate: \`scripts/framediff_run.sh $page $WIDTH\`)"
    done
    echo
    # append the static explanatory sections verbatim
    cat docs/_framediff_notes.md 2>/dev/null || true
} >"$DOC"

echo "[framediff-all] wrote $DOC and $RESULTS/*/"
