#!/usr/bin/env bash
# scripts/framediff_all.sh — run the whole browser-fidelity corpus in TEXT-MODE
# (mono-grid) preview and publish it to docs/browser_framediff_textmode.md.
#
# NOTE: this is NOT the parity signal. It paints the engine's 8px char-grid
# display-list dump (scripts/render_hambrowse_png.py) — now at TRUE font-size with
# proportional advance, but still on the mono grid with no proportional reflow, so
# text position/wrapping diverges from a real browser. The canonical Chrome/Firefox
# parity scorecard is the PIXEL harness scripts/framediff_gfx_all.sh ->
# docs/browser_framediff.md (real lib/htmlpage+lib/htmlpaint renderer).
#
# For every page under tests/framediff/pages/*.html it invokes
# scripts/framediff_run.sh (hambrowse host render-to-PNG vs headless
# chromium/firefox), collects each page's SSIM/brmse/RMSE, and writes a legible
# summary table (SSIM higher==closer, brmse/RMSE lower==closer) plus the
# results-dir paths. Diff/side-by-side PNGs land under build/framediff/<page>/.
#
# USAGE
#   scripts/framediff_all.sh [width]
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

WIDTH="${1:-800}"
CORPUS="tests/framediff/pages"
# The text-dump path is a MONO-GRID preview, NOT the parity signal (it reads the
# 8px char-grid display list; proportional reflow lives only in the pixel
# harness). It publishes a SECONDARY doc so it no longer clobbers the canonical
# pixel scorecard (docs/browser_framediff.md, written by framediff_gfx_all.sh).
DOC="docs/browser_framediff_textmode.md"
RESULTS="build/framediff"
mkdir -p "$RESULTS" docs

# force a clean host-harness build so the table reflects current engine
rm -f build/host/hambrowse_host

pages=("$CORPUS"/*.html)
[ -e "${pages[0]}" ] || { echo "[framediff-all] no corpus pages under $CORPUS"; exit 1; }

declare -A RM_CHR RM_FF NORM_CHR NORM_FF SSIM_CHR SSIM_FF BRMSE_CHR BRMSE_FF
for page in "${pages[@]}"; do
    name="$(basename "$page" .html)"
    echo "==== $name ===="
    bash scripts/framediff_run.sh "$page" "$WIDTH" || echo "[framediff-all] $name had no references"
    sc="$RESULTS/$name/score.txt"
    if [ -f "$sc" ]; then
        # score.txt: engine rmse rmse_norm ae ssim brmse
        while read -r eng rmse norm ae ssim brmse; do
            case "$eng" in
                chromium) RM_CHR[$name]="$rmse"; NORM_CHR[$name]="$norm"
                          SSIM_CHR[$name]="$ssim"; BRMSE_CHR[$name]="$brmse" ;;
                firefox)  RM_FF[$name]="$rmse";  NORM_FF[$name]="$norm"
                          SSIM_FF[$name]="$ssim"; BRMSE_FF[$name]="$brmse" ;;
            esac
        done <"$sc"
    fi
done

# ---- render the summary table into the doc -----------------------------------
ts="$(date -u +%Y-%m-%dT%H:%MZ)"
{
    echo "# Browser fidelity harness (framediff — text-mode preview)"
    echo
    echo "_Auto-generated by \`scripts/framediff_all.sh\` — last run ${ts}, viewport width ${WIDTH}px._"
    echo
    echo "> **This is a MONO-GRID preview, not the parity signal.** It paints the"
    echo "> engine's text-mode display-list dump, which is laid out on an 8px"
    echo "> character grid with NO proportional line-reflow, so text position/wrapping"
    echo "> diverge from a real browser regardless of glyph fidelity. The visualizer"
    echo "> now draws each run at its TRUE CSS font-size (headings render big) with"
    echo "> proportional advance + true text-align re-centring, so it faithfully shows"
    echo "> WHAT THE ENGINE LAID OUT — but for Chrome/Firefox parity use the pixel"
    echo "> scorecard \`docs/browser_framediff.md\` (\`scripts/framediff_gfx_all.sh\`),"
    echo "> which renders through the real \`lib/htmlpage\`+\`lib/htmlpaint\` painter."
    echo
    echo "Metrics: **SSIM** (structural, 0..1, higher==closer) and **brmse**"
    echo "(downsample+blur RMSE, 0..1, lower==closer) reward structure over subpixel"
    echo "AA; raw **RMSE** (ImageMagick 0..65535, 0..1 normalized in parens) is kept for"
    echo "continuity. See \`scripts/framediff_metric.py\`."
    echo
    echo "| Page | SSIM vs chr ↑ | SSIM vs ff ↑ | brmse chr ↓ | brmse ff ↓ | RMSE vs chromium | RMSE vs firefox |"
    echo "|------|--------------:|-------------:|------------:|-----------:|-----------------:|----------------:|"
    for page in "${pages[@]}"; do
        name="$(basename "$page" .html)"
        c="${RM_CHR[$name]:-n/a}"; cn="${NORM_CHR[$name]:-}"
        f="${RM_FF[$name]:-n/a}"; fn="${NORM_FF[$name]:-}"
        sc="${SSIM_CHR[$name]:-n/a}"; sf="${SSIM_FF[$name]:-n/a}"
        bc="${BRMSE_CHR[$name]:-n/a}"; bf="${BRMSE_FF[$name]:-n/a}"
        [ -n "$cn" ] && c="$c ($cn)"
        [ -n "$fn" ] && f="$f ($fn)"
        printf '| %s | %s | %s | %s | %s | %s | %s |\n' \
            "$name" "$sc" "$sf" "$bc" "$bf" "$c" "$f"
    done
    echo
    echo "Side-by-side (hambrowse | reference | heatmap) and heatmap PNGs per page:"
    echo
    for page in "${pages[@]}"; do
        name="$(basename "$page" .html)"
        echo "- \`$name\`: \`$RESULTS/$name/sxs_chromium.png\`, \`$RESULTS/$name/diff_chromium.png\` (regenerate: \`scripts/framediff_run.sh $page $WIDTH\`)"
    done
    echo
    # append the static explanatory sections verbatim
    cat docs/_framediff_notes.md 2>/dev/null || true
} >"$DOC"

echo "[framediff-all] wrote $DOC and $RESULTS/*/"
