#!/usr/bin/env bash
# scripts/framediff_gfx_all.sh — run the whole PIXEL browser-fidelity corpus and
# publish the scorecard the engine team iterates against.
#
# For every page under tests/framediff/pages/*.html it invokes
# scripts/framediff_gfx_run.sh (hambrowse PIXEL render vs headless chromium AND
# firefox), collects each page's RMSE-vs-reference, and writes a ranked summary
# table into docs/browser_framediff.md (worst RMSE first — the biggest
# Chrome/Firefox gaps to close). Diff / side-by-side PNGs land under
# build/framediff_gfx/<page>/ (ephemeral; regenerate with this script).
#
# The hand-written "Ranked pixel-level gaps" section of the doc is preserved
# across runs (this script only regenerates the auto table between the AUTO
# markers); keep the qualitative ranking there, grounded in the heatmaps.
#
# USAGE
#   scripts/framediff_gfx_all.sh [width]
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

WIDTH="${1:-800}"
CORPUS="tests/framediff/pages"
DOC="docs/browser_framediff.md"
RESULTS="build/framediff_gfx"
mkdir -p "$RESULTS" docs

# force a clean pixel-backend build so the table reflects the current engine
rm -f build/host/hambrowse_gfx

pages=("$CORPUS"/*.html)
[ -e "${pages[0]}" ] || { echo "[framediff-gfx-all] no corpus pages under $CORPUS"; exit 1; }

declare -A NORM_CHR NORM_FF RM_CHR RM_FF
for page in "${pages[@]}"; do
    name="$(basename "$page" .html)"
    echo "==== $name ===="
    bash scripts/framediff_gfx_run.sh "$page" "$WIDTH" || echo "[framediff-gfx-all] $name had no references"
    sc="$RESULTS/$name/score.txt"
    if [ -f "$sc" ]; then
        while read -r eng rmse norm ae; do
            case "$eng" in
                chromium) RM_CHR[$name]="$rmse"; NORM_CHR[$name]="$norm" ;;
                firefox)  RM_FF[$name]="$rmse";  NORM_FF[$name]="$norm" ;;
            esac
        done <"$sc"
    fi
done

# ---- rank pages by mean normalized RMSE (worst first) ------------------------
ranked="$(for page in "${pages[@]}"; do
    name="$(basename "$page" .html)"
    cn="${NORM_CHR[$name]:-}"; fn="${NORM_FF[$name]:-}"
    mean="$(awk -v a="$cn" -v b="$fn" 'BEGIN{
        n=0; s=0; if(a!=""){s+=a;n++} if(b!=""){s+=b;n++}
        if(n==0){print "999"} else {printf "%.6f", s/n} }')"
    printf '%s\t%s\n' "$mean" "$name"
done | sort -rn)"

# ---- build the auto table ----------------------------------------------------
ts="$(date -u +%Y-%m-%dT%H:%MZ)"
tbl="$(mktemp)"
{
    echo "<!-- AUTO:framediff-gfx BEGIN (regenerated by scripts/framediff_gfx_all.sh) -->"
    echo "_Last run ${ts}, viewport width ${WIDTH}px. Ranked worst-first by mean"
    echo "normalized RMSE across the two references._"
    echo
    echo "| Rank | Page | RMSE vs chromium | RMSE vs firefox | mean norm |"
    echo "|-----:|------|-----------------:|----------------:|----------:|"
    rank=0
    while IFS=$'\t' read -r mean name; do
        rank=$((rank+1))
        c="${RM_CHR[$name]:-n/a}"; cn="${NORM_CHR[$name]:-}"
        f="${RM_FF[$name]:-n/a}"; fn="${NORM_FF[$name]:-}"
        [ -n "$cn" ] && c="$c ($cn)"
        [ -n "$fn" ] && f="$f ($fn)"
        printf '| %d | %s | %s | %s | %s |\n' "$rank" "$name" "$c" "$f" "$mean"
    done <<<"$ranked"
    echo
    echo "Per-page artifacts (hambrowse-pixel | reference | heatmap):"
    echo
    for page in "${pages[@]}"; do
        name="$(basename "$page" .html)"
        echo "- \`$name\`: \`$RESULTS/$name/sxs_chromium.png\`, \`$RESULTS/$name/sxs_firefox.png\`, \`$RESULTS/$name/diff_chromium.png\`"
    done
    echo
    echo "Regenerate: \`scripts/framediff_gfx_all.sh $WIDTH\`. Single page: \`scripts/framediff_gfx_run.sh $CORPUS/<name>.html $WIDTH\`."
    echo "<!-- AUTO:framediff-gfx END -->"
} >"$tbl"

# ---- splice the auto table into the doc between the markers ------------------
if [ -f "$DOC" ] && grep -q 'AUTO:framediff-gfx BEGIN' "$DOC"; then
    python3 - "$DOC" "$tbl" <<'PY'
import sys, re
doc, tbl = sys.argv[1], sys.argv[2]
body = open(doc, encoding="utf-8").read()
new = open(tbl, encoding="utf-8").read().rstrip("\n")
body = re.sub(r"<!-- AUTO:framediff-gfx BEGIN.*?AUTO:framediff-gfx END -->",
              new, body, flags=re.S)
open(doc, "w", encoding="utf-8").write(body)
PY
else
    echo "[framediff-gfx-all] WARN: AUTO markers not found in $DOC; appending table"
    { echo; cat "$tbl"; } >>"$DOC"
fi
rm -f "$tbl"

echo "[framediff-gfx-all] wrote $DOC and $RESULTS/*/"
echo "== ranked (worst first) =="
echo "$ranked"
