#!/usr/bin/env python3
"""Regenerate user/linux-vk-spv.h from scripts/shaders/vk2d_raster.comp.spv.

The Linux-Vulkan backend (user/linux-vk.c) embeds its compute rasterizer's
SPIR-V rather than reading a file, because the Hamnix root has no scripts/
tree.  Run this after recompiling the .comp with scripts/shaderc_compile.c.
"""
import struct
import sys

SPV = "scripts/shaders/vk2d_raster.comp.spv"
OUT = "user/linux-vk-spv.h"
data = open(SPV, "rb").read()
if len(data) % 4:
    sys.exit("%s is not a whole number of 32-bit words" % SPV)
words = struct.unpack("<%dI" % (len(data) // 4), data)
lines = [
    "/* user/linux-vk-spv.h — GENERATED by scripts/gen_linux_vk_spv.py. */",
    "#ifndef HAMNIX_LINUX_VK_SPV_H",
    "#define HAMNIX_LINUX_VK_SPV_H",
    "#include <stdint.h>",
    "static const uint32_t hvk_spv_vk2d_raster[] = {",
]
for i in range(0, len(words), 8):
    lines.append("    " + " ".join("0x%08xu," % x for x in words[i:i + 8]))
lines += ["};", "#define HVK_SPV_VK2D_RASTER_BYTES (sizeof hvk_spv_vk2d_raster)",
          "#endif"]
open(OUT, "w").write("\n".join(lines) + "\n")
print("%s: %d words" % (OUT, len(words)))
