#!/usr/bin/env bash
# scripts/test_x509_chain_policy.sh — RFC 5280 §6.1 path-validation POLICY
# regression for the native X.509 chain validator.
#
# Builds tests/test_x509_chain_policy.ad (generated by
# scripts/gen_x509_chain_fixture.py) as a userland x86_64 ELF, plants it at
# /bin/test_x509_chain_policy, boots QEMU + hamsh, runs the binary, and
# greps the serial log for the [x509-chain] PASS banner.
#
# The fixture drives lib/x509/chain.ad::validate_cert_chain over a real
# ECDSA-P256 root->intermediate->leaf chain plus crafted negative cases that
# each exercise one RFC 5280 §6.1 policy rule:
#   (1) legitimate chain                         => 1
#   (2) leaf signature bit-flipped               => 0
#   (3) wrong host                               => 0
#   (4) expired leaf (now past notAfter)         => 0
#   (5) empty CA store                           => 0
#   (6) intermediate is NOT a CA                 => 0
#   (7) intermediate lacks keyCertSign           => 0
#   (8) leaf has an unknown CRITICAL extension   => 0
#   (9) leaf EKU lacks serverAuth                => 0
#  (10) issuer/subject DN mismatch               => 0
#  (11) pathLenConstraint=0 violated             => 0
#
# Most negatives reject BEFORE any signature verify; only cases 1, 2 and 11
# drive ECDSA-P256 verifies, so the QEMU budget is ~30s of EC math.
#
# PASS criterion: "[x509-chain] failures=0" AND "[x509-chain] PASS" both
# present in the serial log, with no "[x509-chain] FAIL:" lines.
# Shape borrowed from scripts/test_chain_validate.sh.

. "$(dirname "$0")/_build_lock.sh"

set -euo pipefail
PROJ_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJ_ROOT"

ELF=build/hamnix-kernel.elf
HAMSH_ELF=build/user/hamsh.elf
TEST_ELF=build/user/test_x509_chain_policy.elf

echo "[test_x509_chain_policy] (1/5) Build userland (hamsh + coreutils)"
bash scripts/build_user.sh >/dev/null
bash scripts/build_modules.sh >/dev/null

echo "[test_x509_chain_policy] (2/5) Build tests/test_x509_chain_policy.ad -> $TEST_ELF"
python3 -m compiler.adder compile \
    --target=x86_64-adder-user \
    tests/test_x509_chain_policy.ad \
    -o "$TEST_ELF" >/dev/null

echo "[test_x509_chain_policy] (3/5) Plant /etc/hamsh.rc that auto-runs the fixture"
# Drive the binary from the boot rc rather than interactive keystrokes:
# fixed-sleep keystroke timing regresses when boot slows under load (see
# memory/feedback_interactive_test_wait_for_prompt.md). The rc runs at boot,
# deterministically, before the shell prompt loop.
RC_TMP=$(mktemp /tmp/hamsh-rc-x509chain.XXXXXX.rc)
cat > "$RC_TMP" <<'EOF'
echo X509_CHAIN_RC_START
/bin/test_x509_chain_policy
echo X509_CHAIN_RC_DONE
exit
EOF

echo "[test_x509_chain_policy] (3b/5) Plant /init = hamsh + /bin/test_x509_chain_policy in cpio"
HAMNIX_HAMSH_RC="$RC_TMP" INIT_ELF="$HAMSH_ELF" \
    python3 scripts/build_initramfs.py >/dev/null

echo "[test_x509_chain_policy] (4/5) Rebuild kernel image"
python3 -m compiler.adder compile \
    --target=x86_64-bare-metal \
    init/main.ad \
    -o "$ELF" >/dev/null

echo "[test_x509_chain_policy] (5/5) Boot QEMU + auto-run /bin/test_x509_chain_policy"
LOG=$(mktemp)
trap 'rm -f "$LOG" "$RC_TMP"; INIT_ELF=build/user/init.elf python3 scripts/build_initramfs.py >/dev/null' EXIT

set +e
timeout 180s qemu-system-x86_64 \
    -kernel "$ELF" \
    -smp 2 \
    -nographic \
    -no-reboot \
    -m 256M \
    -monitor none \
    -serial stdio \
    > "$LOG" 2>&1
rc=$?
set -e

echo "[test_x509_chain_policy] --- captured output ---"
cat "$LOG"
echo "[test_x509_chain_policy] --- end output ---"

fail=0

if grep -F -q "[x509-chain] start" "$LOG"; then
    echo "[test_x509_chain_policy] OK: fixture ran"
else
    echo "[test_x509_chain_policy] MISS: fixture banner missing"
    fail=1
fi

if grep -F -q "[x509-chain] FAIL:" "$LOG"; then
    echo "[test_x509_chain_policy] MISS: per-assertion FAIL line(s) present:"
    grep -F "[x509-chain] FAIL:" "$LOG" | sed 's/^/  /'
    fail=1
else
    echo "[test_x509_chain_policy] OK: no per-assertion FAIL lines"
fi

if grep -F -q "[x509-chain] failures=0" "$LOG"; then
    echo "[test_x509_chain_policy] OK: failures=0"
else
    echo "[test_x509_chain_policy] MISS: failures=0 absent"
    fail=1
fi

if grep -F -q "[x509-chain] PASS" "$LOG"; then
    echo "[test_x509_chain_policy] OK: fixture reached PASS"
else
    echo "[test_x509_chain_policy] MISS: PASS line absent"
    fail=1
fi

if [ "$fail" -ne 0 ]; then
    echo "[test_x509_chain_policy] FAIL (qemu rc=$rc)"
    exit 1
fi

echo "[test_x509_chain_policy] PASS"
